
drop table TmpLLU
SELECT     PURCHTABLE.PURCHID, PURCHTABLE.DC_CONNECTIONID, DC_PURCHPROPOSALLINE.PURCHPROPOSALID, DC_PURCHPROPOSALLINE.ITEMID, 
                      DC_PURCHPROPOSALLINE.QTY, DC_PURCHPROPOSALLINE.CONNECTIONID, DC_PURCHPROPOSALLINE.PURCHPROPOSALSTATUS, PurchTable.DC_SGShipped,
					  PurchTable.INVOICEACCOUNT as INVOICEACCOUNT
into TmpLLU
FROM         PURCHTABLE INNER JOIN
                      DC_PURCHPROPOSALLINE ON PURCHTABLE.PURCHID = DC_PURCHPROPOSALLINE.PURCHID AND 
                      PURCHTABLE.DC_CONNECTIONID <> DC_PURCHPROPOSALLINE.CONNECTIONID AND
					  PurchTable.dataareaid = DC_PURCHPROPOSALLINE.DATAAREAID
WHERE PurchTable.dataareaid = 'KNI'			

select purchid, dc_connectionid as connection, connectionid as connection_orig, count(*) as antal, DC_SGShipped, 
	LTRIM(INVOICEACCOUNT)+' '+(select name from vendtable where accountnum = TmpLLU.INVOICEACCOUNT and vendtable.dataareaid = 'KNI') as VendName,
	dbo.lp_year_mth_date((SELECT     LASTORDERDATE
		FROM         DC_PURCHCONNECTIONTABLE
		WHERE     (DC_CONNECTIONID = TmpLLU.dc_connectionid) and dataareaid = 'KNI')+
	(SELECT top 1    DC_INVENTPACKINGCODETABLE.DC_LASTORDERDATE_OFFSET
		FROM         DC_INVENTPACKINGCODETABLE INNER JOIN
                      INVENTTABLE ON DC_INVENTPACKINGCODETABLE.DATAAREAID = INVENTTABLE.DATAAREAID AND 
						DC_INVENTPACKINGCODETABLE.INVENTPACKINGCODE = INVENTTABLE.DC_INVENTPACKINGCODE INNER JOIN
                      PURCHLINE ON DC_INVENTPACKINGCODETABLE.DATAAREAID = PURCHLINE.DATAAREAID AND 
						INVENTTABLE.ITEMID = PURCHLINE.ITEMID and DC_INVENTPACKINGCODETABLE.dataareaid = 'KNI' AND
						PURCHLINE.PURCHID = TmpLLU.PURCHID)) as LastOrderDate_PO,
	dbo.lp_year_mth_date((SELECT     LASTORDERDATE
		FROM         DC_PURCHCONNECTIONTABLE
		WHERE     (DC_CONNECTIONID = TmpLLU.connectionid) and dataareaid = 'KNI')+
	(SELECT top 1    DC_INVENTPACKINGCODETABLE.DC_LASTORDERDATE_OFFSET
		FROM         DC_INVENTPACKINGCODETABLE INNER JOIN
                      INVENTTABLE ON DC_INVENTPACKINGCODETABLE.DATAAREAID = INVENTTABLE.DATAAREAID AND 
						DC_INVENTPACKINGCODETABLE.INVENTPACKINGCODE = INVENTTABLE.DC_INVENTPACKINGCODE INNER JOIN
                      PURCHLINE ON DC_INVENTPACKINGCODETABLE.DATAAREAID = PURCHLINE.DATAAREAID AND 
						INVENTTABLE.ITEMID = PURCHLINE.ITEMID and DC_INVENTPACKINGCODETABLE.dataareaid = 'KNI' AND
						PURCHLINE.PURCHID = TmpLLU.PURCHID)) as LastOrderDate_Orig

	
	from TmpLLU 
 --where DC_SGShipped <> '19000101'
group by purchid, dc_connectionid, connectionid,DC_SGShipped, invoiceaccount

-- select * from tmpLLU
--select max(purchid) from purchtable