ALTER VIEW LP_CustStat2
AS 
SELECT INVENTTRANS.ITEMID,
	-1* SUM(dbo.INVENTTRANS.QTY) AS Qty, 
    CASE WHEN sum(dbo.CUSTINVOICETRANS.QTY) <> 0 THEN
											((SUM(dbo.CUSTINVOICETRANS.LINEAMOUNTMST)) 
												*(-1*SUM(dbo.INVENTTRANS.QTY)/sum(dbo.CUSTINVOICETRANS.QTY)))
										   ELSE
											0
										   END
									AS SalesAmountMST,
	-1*(sum(INVENTTRANS.COSTAMOUNTPOSTED)+sum(INVENTTRANS.COSTAMOUNTADJUSTMENT)) as CostAmount,
	(SELECT top 1 AMOUNT FROM PRICEDISCTABLE WHERE RELATION = 4 AND ITEMCODE = 0 AND ACCOUNTCODE = 1 AND  (ITEMRELATION = INVENTTRANS.ITEMID) AND 
		(ACCOUNTRELATION = '1') AND (FROMDATE <= INVENTTRANS.DATEFINANCIAL) AND ((TODATE >= INVENTTRANS.DATEFINANCIAL) OR (TODATE = '19000101'))) as salgspris1
		
FROM         INVENTTRANS  INNER JOIN
                      CUSTINVOICETRANS ON CUSTINVOICETRANS.INVENTTRANSID = INVENTTRANS.INVENTTRANSID AND CUSTINVOICETRANS.DATAAREAID = INVENTTRANS.DATAAREAID AND 
                      CUSTINVOICETRANS.INVOICEID = INVENTTRANS.INVOICEID AND CUSTINVOICETRANS.INVOICEDATE = INVENTTRANS.DATEFINANCIAL
where INVENTTRANS.DATEFINANCIAL >= '20080101' AND INVENTTRANS.DATEFINANCIAL <= '20081231'
GROUP BY INVENTTRANS.ITEMID,inventtrans.datefinancial
GO
ALTER VIEW LP_CustStat3
AS 
SELECT     ITEMID, sum(CostAmount) as CostAmount, sum(Qty) as Qty, sum(SalesAmountMST) as SalesAmountMST, sum(SalesAmountMST) - sum(CostAmount) AS DB,salgspris1,
	(SELECT     ITEMNAME
		FROM         INVENTTABLE
			WHERE     (ITEMID = LP_CustStat2.ItemId)) AS ItemName
FROM         LP_CustStat2
group by itemid,salgspris1
GO

select top 700 * from LP_CustStat3 order by DB DESC