sp_helpstats 'dbo.ledgertrans', 'ALL'

DBCC SHOW_STATISTICS('dbo.ledgertrans', I_225ACDATE)
DBCC SHOW_STATISTICS('dbo.ledgertrans', I_225DATEIDX)
DBCC SHOW_STATISTICS('dbo.ledgertrans', I_225FURTHERPOSTINGTYPE)
DBCC SHOW_STATISTICS('dbo.ledgertrans', I_225JOURNALIZEIDX)
DBCC SHOW_STATISTICS('dbo.ledgertrans', I_225POSTINGJOURNAIDXL)
DBCC SHOW_STATISTICS('dbo.ledgertrans', I_225RECID)
DBCC SHOW_STATISTICS('dbo.ledgertrans', I_225TRANSACTIONLOGIDX)
DBCC SHOW_STATISTICS('dbo.ledgertrans', I_225VOUCHERDATEIDX)

