SELECT  PURCHPROPOSALID, ITEMID, CONNECTIONID, VENDACCOUNT, LOCKED, APPROVED, PURCHID
FROM         DC_PURCHPROPOSALLINE
where purchproposalid = '00758477'

SELECT     PURCHPROPOSALID, ITEMID, CONNECTIONID, VENDACCOUNT, LOCKED, APPROVED, PURCHID, PURCHPROPOSALSTATUS
FROM         DC_PURCHPROPOSALLINE
WHERE     (LOCKED = 1) AND (PURCHID = '') AND (VENDACCOUNT = dbo.LP_STRLFIX('8258', 20)) and connectionid = '842'

SELECT     PURCHPROPOSALID, ITEMID, CONNECTIONID, VENDACCOUNT, LOCKED, APPROVED, PURCHID, PURCHPROPOSALSTATUS, REFPURCHRECID, 
                      CREATEDDATE, CREATEDTIME, MODIFIEDDATE, MODIFIEDTIME
FROM         DC_PURCHPROPOSALLINE
WHERE     (LOCKED = 1) AND (REFPURCHRECID = 0) AND (PURCHPROPOSALSTATUS = 20) and createddate > '20081105'
--and purchproposalid = '00758477'

update DC_PURCHPROPOSALLINE
	set purchid = '', locked = 0
WHERE     (LOCKED = 1) AND (REFPURCHRECID = 0) and (VENDACCOUNT = dbo.LP_STRLFIX('8258', 20)) and PURCHPROPOSALSTATUS = 20

