drop table inventtableshadow
SELECT     CONFIGTABLE.CONFIGID, INVENTTABLE.ITEMGROUPID, INVENTTABLE.ITEMID+'_'+CONFIGTABLE.CONFIGID as ITEMID, INVENTTABLE.ITEMNAME, INVENTTABLE.ITEMTYPE, 
                      INVENTTABLE.PURCHMODEL, INVENTTABLE.HEIGHT, INVENTTABLE.SALESMODEL, INVENTTABLE.COSTGROUPID, 
                      INVENTTABLE.REQGROUPID, INVENTTABLE.PRIMARYVENDORID, INVENTTABLE.NETWEIGHT, INVENTTABLE.DEPTH, INVENTTABLE.UNITVOLUME, 
                      INVENTTABLE.BOMUNITID, INVENTTABLE.DENSITY, INVENTTABLE.DIMENSION, INVENTTABLE.DIMENSION2_, 
                      INVENTTABLE.DIMENSION3_, INVENTTABLE.COSTMODEL, INVENTTABLE.USEALTITEMID, INVENTTABLE.ALTITEMID, INVENTTABLE.INTRACODE, 
                      INVENTTABLE.BOMMANUALCONSUMP, INVENTTABLE.BOMMANUALRECEIPT, INVENTTABLE.STOPEXPLODE, 
                       INVENTTABLE.PHANTOM, INVENTTABLE.INTRAUNIT, INVENTTABLE.BOMLEVEL, 
                      INVENTTABLE.BATCHNUMGROUPID, INVENTTABLE.AUTOREPORTFINISHED, INVENTTABLE.ORIGCOUNTRYID, INVENTTABLE.STATISTICSFACTOR, 
                      INVENTTABLE.ALTCONFIGID, INVENTTABLE.STANDARDCONFIGID,  INVENTTABLE.PRODPOOLID, 
                      INVENTTABLE.PROPERTYID, INVENTTABLE.ABCTIEUP, INVENTTABLE.ABCREVENUE, INVENTTABLE.ABCVALUE, 
                      INVENTTABLE.ABCCONTRIBUTIONMARGIN, INVENTTABLE.COMMISSIONGROUPID,
                      INVENTTABLE.CONFIGURABLE, INVENTTABLE.SALESPERCENTMARKUP, 
                      /*INVENTTABLE.SALESCONTRIBUTIONRATIO, INVENTTABLE.SALESPRICEMODELBASIC, INVENTTABLE.MINAVERAGESETTLE, 
                      INVENTTABLE.NAMEALIAS, INVENTTABLE.PRODGROUPID, INVENTTABLE.PROJCATEGORYID, INVENTTABLE.GROSSDEPTH, 
                      INVENTTABLE.GROSSdatTH, INVENTTABLE.GROSSHEIGHT, INVENTTABLE.STANDARDPALLETQUANTITY, INVENTTABLE.QTYPERLAYER, 
                      INVENTTABLE.SORTCODE, INVENTTABLE.CONFIGSIMILAR, INVENTTABLE.SERIALNUMGROUPID, INVENTTABLE.DIMGROUPID, 
                      INVENTTABLE.MODELGROUPID, INVENTTABLE.ITEMBUYERGROUPID, INVENTTABLE.TAXPACKAGINGQTY, INVENTTABLE.DEL_TEMPLATE, 
                      INVENTTABLE.WMSPALLETTYPEID, INVENTTABLE.ORIGSTATEID, INVENTTABLE.STOPEXPLODEPRICE, INVENTTABLE.WMSPICKINGQTYTIME, 
                      INVENTTABLE.TARAWEIGHT, INVENTTABLE.PACKAGINGGROUPID, INVENTTABLE.SCRAPVAR, INVENTTABLE.SCRAPCONST, 
                      INVENTTABLE.STANDARDINVENTCOLORID, INVENTTABLE.STANDARDINVENTSIZEID, INVENTTABLE.ITEMDIMCOMBINATIONAUTOCREATE, 
                      INVENTTABLE.ITEMDIMCOSTPRICE, INVENTTABLE.ALTINVENTSIZEID, INVENTTABLE.ALTINVENTCOLORID, INVENTTABLE.ITEMIDMASKED_WDX, 
                      INVENTTABLE.HEADTYPE_dat, INVENTTABLE.STATISTIKID_dat, INVENTTABLE.STATISTIKID2_dat, INVENTTABLE.PRODLOCATIONID, 
                      INVENTTABLE.PRODUCTTYPEID_EMS, INVENTTABLE.MASTERITEMID_EMS, INVENTTABLE.MASTERITEM_EMS, 
                      INVENTTABLE.INVENTPROJECTID_WDX, INVENTTABLE.DEFAULTCONFIGID_EMS, INVENTTABLE.SERIALNUMCHECKGROUPID, 
                      INVENTTABLE.CEVERSION_WDX, INVENTTABLE.MODIFIEDDATE, INVENTTABLE.MODIFIEDTIME, INVENTTABLE.MODIFIEDBY, 
                      INVENTTABLE.CREATEDDATE, INVENTTABLE.CREATEDTIME, INVENTTABLE.CREATEDBY, INVENTTABLE.DATAAREAID, INVENTTABLE.ITEMIDCONFIG, 
                      INVENTTABLE.TECHNICALDESCRIPTION,*/ '999999999' AS RECID
INTO		InventTableShadow
FROM         INVENTTABLE INNER JOIN
                      CONFIGTABLE ON INVENTTABLE.ITEMID = CONFIGTABLE.ITEMID 
			AND CONFIGTABLE.DATAAREAID = INVENTTABLE.DATAAREAID
			AND CONFIGTABLE.DATAAREAID = 'dat'
GO
	Declare @NewRecId   as INT
	declare @count		as INT

	select @Count = count(*) from inventTableShadow
	select * from systemsequences
		WHERE ID = -1 AND TABID = 0 AND Dataareaid = 'dat'	

		UPDATE dbo.SystemSequences
			SET    @NewRecid  = NextVal - 1,
					NextVal    = NextVal + @Count 
			WHERE ID = -1 AND TABID = 0 AND Dataareaid = 'dat'	

		update dbo.inventTableShadow set @NewRecid = @NewRecid + 1,
						 recid = cast(@NewRecid as varchar(10));

	select top 100 itemid, recid from InventTableShadow
	select * from systemsequences
		WHERE ID = -1 AND TABID = 0 AND Dataareaid = 'dat'	
	
select * from inventTableShadow

--select * from configtable
--	where  configtable.dataareaid = 'dat'	
/*
select count(*) from inventtable, configtable
	where configtable.configid <> ''
	and   configtable.dataareaid = 'dat'
	and   inventtable.dataareaid = 'dat'
	and   inventtable.itemid = configtable.itemid

select count(*) from configtable
	where  configtable.dataareaid = 'dat'	


select top 100 count(*) as cnt, itemid from configtable
	where  configtable.dataareaid = 'dat'
	group by itemid
	order by cnt desc

select top 100 count(*) as cnt, itemid from configtable
	where  configtable.dataareaid = 'dat'
	group by itemid
	order by cnt desc


select * from configtable
	where  configtable.dataareaid = 'dat'
	and		configtable.itemid = '5 500 0021'

*/