-- =============================================
-- Create View template
-- =============================================
USE ax30_develop
GO

IF object_id(N'CustInventStatistics', 'V') IS NOT NULL
	DROP VIEW CustInventStatistics
GO

CREATE VIEW CustInventStatistics AS
SELECT     INVENTTRANS.ITEMID, INVENTTABLE.ITEMNAME, CUSTTABLE.ACCOUNTNUM, CUSTTABLE.NAME, CUSTTABLE.CUSTGROUP, 
                      INVENTTABLE.ITEMGROUPID, INVENTTRANS.STATUSISSUE, SUM(INVENTTRANS.QTY) AS QTY, SUM(INVENTTRANS.COSTAMOUNTPOSTED) 
                      AS COSTAMOUNTPOSTED, dbo.F_ISO_YEAR_WEEK_DAY_OF_WEEK(INVENTTRANS.DATEFINANCIAL) AS YRWK, 
                      SUM(INVENTTRANS.COSTAMOUNTADJUSTMENT) AS COSTAMOUNTADJUSTMENT, INVENTDIM.INVENTLOCATIONID, CUSTTABLE.LINEOFBUSINESSID, 
                      CUSTTABLE.SALESPOOLID, CUSTTABLE.STATISTICSGROUP, CUSTTABLE.COUNTRY, CUSTTABLE.INVOICEACCOUNT, 
                      CUSTINVOICETRANS.SALESUNIT, CUSTINVOICETRANS.COMMISSAMOUNTMST, CUSTINVOICETRANS.SALESGROUP, 
                      CUSTINVOICETRANS.LINEAMOUNTMST, CUSTINVOICETRANS.DIMENSION AS Department, CUSTINVOICETRANS.DIMENSION2_ AS Costcenter, 
                      CUSTINVOICETRANS.DIMENSION3_ as Purpose
FROM         INVENTTRANS INNER JOIN
                      CUSTTABLE ON INVENTTRANS.DATAAREAID = CUSTTABLE.DATAAREAID AND INVENTTRANS.CUSTVENDAC = CUSTTABLE.ACCOUNTNUM INNER JOIN
                      INVENTTABLE ON INVENTTRANS.ITEMID = INVENTTABLE.ITEMID AND INVENTTRANS.DATAAREAID = INVENTTABLE.DATAAREAID INNER JOIN
                      INVENTDIM ON INVENTTRANS.DATAAREAID = INVENTDIM.DATAAREAID AND INVENTTRANS.INVENTDIMID = INVENTDIM.INVENTDIMID INNER JOIN
                      CUSTINVOICETRANS ON CUSTTABLE.DATAAREAID = CUSTINVOICETRANS.DATAAREAID AND 
                      INVENTTRANS.INVENTTRANSID = CUSTINVOICETRANS.INVENTTRANSID
WHERE     (INVENTTRANS.STATUSRECEIPT = '0')
GROUP BY INVENTTRANS.ITEMID, INVENTTABLE.ITEMNAME, CUSTTABLE.ACCOUNTNUM, CUSTTABLE.NAME, CUSTTABLE.CUSTGROUP, 
                      INVENTTABLE.ITEMGROUPID, dbo.F_ISO_YEAR_WEEK_DAY_OF_WEEK(INVENTTRANS.DATEFINANCIAL), INVENTTRANS.STATUSISSUE, 
                      INVENTDIM.INVENTLOCATIONID, CUSTTABLE.LINEOFBUSINESSID, CUSTTABLE.CUSTGROUP, CUSTTABLE.SALESPOOLID, 
                      CUSTTABLE.STATISTICSGROUP, CUSTTABLE.COUNTRY, CUSTTABLE.INVOICEACCOUNT, CUSTINVOICETRANS.SALESUNIT, 
                      CUSTINVOICETRANS.COMMISSAMOUNTMST, CUSTINVOICETRANS.SALESGROUP, CUSTINVOICETRANS.LINEAMOUNTMST,
                      CUSTINVOICETRANS.DIMENSION, CUSTINVOICETRANS.DIMENSION2_, CUSTINVOICETRANS.DIMENSION3_

