drop table CustTableTmp2
go
create table CustTableTmp2 (CustAccount nvarchar(20),CustName nvarchar(50),CustGrp nvarchar(10))
go
bulk insert CustTableTmp2 from 'c:\temp\custview.txt'
   WITH
     (  FIELDTERMINATOR =';',
        ROWTERMINATOR = '\n')

select count(*) from inventtrans


use axdb_lp
drop table LP_LedgerBal
create table LP_LedgerBal (LedAcc nvarchar(10),LedAccname nvarchar(30), periodcode nvarchar(10),amount decimal)	
GO
CREATE VIEW LP_LedgerTableView as 
SELECT     LTRIM(LEDGERTABLE.ACCOUNTNUM) as LedAcc, LTRIM(LEDGERTABLE.ACCOUNTNAME) as LedAccname, 
			cast(datepart(yyyy,LEDGERPERIOD.PERIODSTART) as nvarchar)+'-'+ right('00'+cast(datepart(mm,LEDGERPERIOD.PERIODSTART) as nvarchar),2) as periodcode,
                      SUM(LEDGERTRANS.AMOUNTMST) AS amount
FROM         LEDGERTABLE INNER JOIN
                      LEDGERPERIOD ON LEDGERTABLE.DATAAREAID = LEDGERPERIOD.DATAAREAID AND LEDGERPERIOD.PERIODSTATUS = 1 INNER JOIN
                      LEDGERTRANS ON LEDGERTABLE.ACCOUNTNUM = LEDGERTRANS.ACCOUNTNUM AND LEDGERTABLE.DATAAREAID = LEDGERTRANS.DATAAREAID
							 AND LEDGERTRANS.TRANSDATE >= LEDGERPERIOD.PERIODSTART AND LEDGERTRANS.TRANSDATE <= LEDGERPERIOD.PERIODEND 
							 AND LEDGERTRANS.PERIODCODE = 1
where LEDGERPERIOD.PERIODSTART >= '20080101'
GROUP BY LEDGERTABLE.ACCOUNTNUM, LEDGERTABLE.ACCOUNTNAME, LEDGERPERIOD.PERIODSTART, LEDGERPERIOD.PERIODEND, LEDGERPERIOD.PERIODSTATUS


insert into LP_LedgerBal select * from LP_LedgerTableView
SELECT     LTRIM(LEDGERTABLE.ACCOUNTNUM) as LedAcc, LTRIM(LEDGERTABLE.ACCOUNTNAME) as LedAccname, 
			cast(datepart(yyyy,LEDGERPERIOD.PERIODSTART) as nvarchar)+'-'+ right('00'+cast(datepart(mm,LEDGERPERIOD.PERIODSTART) as nvarchar),2) as periodcode,
                      SUM(LEDGERTRANS.AMOUNTMST) AS amount
FROM         LEDGERTABLE INNER JOIN
                      LEDGERPERIOD ON LEDGERTABLE.DATAAREAID = LEDGERPERIOD.DATAAREAID AND LEDGERPERIOD.PERIODSTATUS = 1 INNER JOIN
                      LEDGERTRANS ON LEDGERTABLE.ACCOUNTNUM = LEDGERTRANS.ACCOUNTNUM AND LEDGERTABLE.DATAAREAID = LEDGERTRANS.DATAAREAID
							 AND LEDGERTRANS.TRANSDATE >= LEDGERPERIOD.PERIODSTART AND LEDGERTRANS.TRANSDATE <= LEDGERPERIOD.PERIODEND 
							 AND LEDGERTRANS.PERIODCODE = 1
where LEDGERPERIOD.PERIODSTART >= '20080101'
GROUP BY LEDGERTABLE.ACCOUNTNUM, LEDGERTABLE.ACCOUNTNAME, LEDGERPERIOD.PERIODSTART, LEDGERPERIOD.PERIODEND, LEDGERPERIOD.PERIODSTATUS
