DECLARE @TRS Varchar(10)
DECLARE @TRSNo INT, @MaxHoursINIT Varchar(10), @PCSINIT Varchar(10)
SET @TRSNo = 49000
WHILE (@TRSNo<49100)
BEGIN
	SET @TRS = CAST(@TRSNo as Varchar(10))
	DECLARE MaxHours CURSOR FOR
		select dbo.MaxHoursOnTRS(@TRS) AS MaxHoursOnTRS, @TRS as TRS
	DECLARE TRSReport CURSOR FOR
		select LATESTCONTACTPCSINIT FROM dbo.PCS_TRSREPORT
			WHERE PCS_TRSID = @TRS
	OPEN MaxHours
	OPEN TRSReport
	FETCH NEXT FROM MaxHours INTO @MaxHoursINIT, @TRS
	FETCH NEXT FROM TRSReport INTO @PCSINIT
	CLOSE MaxHours
	DEALLOCATE MaxHours
	CLOSE TRSReport
	DEALLOCATE TRSReport
	IF (@PCSINIT <> @MaxHoursINIT)
		select N'TRS '+@TRS+N' @PCSINIT:'+@PCSINIT+N'  @MaxHoursINIT:'+@MaxHoursINIT
	SET @TRSNo = @TRSNo + 1
END;