use ax30_develop
--CREATE TABLE #T22(TRS Varchar(10),UserId Varchar(10), TotalTime INT);

SELECT TR_REPORTTIME.TRS, TR_REPORTTIME.USERID, SUM(TR_REPORTTIME.TOTALTIME) AS ToTime
			INTO #T23
			FROM         dbo.TR_REPORTTIME, TR_EMPLTABLE 
			WHERE	(TR_REPORTTIME.USERID = TR_EMPLTABLE.TR_EMPLID)
			AND		(TR_EMPLTABLE.TR_DEPT <> '63') 
	--		AND		(TR_REPORTTIME.TRS >= '49000')
	--		AND		(TR_REPORTTIME.TRS <= '49100') --'49638')
			GROUP BY TR_REPORTTIME.TRS,TR_REPORTTIME.USERID
UPDATE PCS_TRSREPORT SET LATESTCONTACTPCSINIT = (SELECT TOP 1 
			WHERE PCS_TRSID = @TRS

SELECT * FROM #T23 ORDER BY TRS
DROP TABLE #T23
