--Rename batchjobs
--use SUPPORT_AX2012
/*select CAPTION from batch group by caption
select batchjob.CAPTION, batch.CAPTION from batch 
join batchjob on
batchjob.recid = batch.batchjobid
where batchjob.status = 1 or batchjob.status = 2*/
 
update batchjob set caption = 'SOP: AIF Inbound' where caption = 'AIF Inbound 2'
update batchjob set caption = 'SOP: AIF Outbound' where caption = 'AIF Outbound 2'
update batchjob set caption = 'FIN: Import bank return files from AMC' where caption = 'ALL - Import bank return files from AMC'
update batchjob set caption = 'COM: Partner Price changes' where caption = 'ALL - Partner Price changes'
update batchjob set caption = 'SYS: Automatic role assignment' where caption = 'Automatic role assignment'
update batchjob set caption = 'COM: Import item pictures' where caption = 'COM Import item pictures'
update batchjob set caption = 'COM: Update item tax groups on item ALL' where caption = 'COM Update item tax groups on item ALL'
update batchjob set caption = 'FIN: DE01 - Calculate statement' where caption = 'DE01 - Calculate statement'
update batchjob set caption = 'FIN: DE01 - Post statement' where caption = 'DE01 - Post statement'
update batchjob set caption = 'FIN: DE01 - Recalculate inventory' where caption = 'DE01 - Recalculate inventory'
update batchjob set caption = 'RET: DE01 - Update employee discounts info subcodes' where caption = 'DE01 - Update employee discounts info subcodes'
update batchjob set caption = 'FIN: DE03 - Calculate statement' where caption = 'DE03 - Calculate statement'
update batchjob set caption = 'FIN: DE03 - Post statement' where caption = 'DE03 - Post statement'
update batchjob set caption = 'FIN: DE03 - Recalculate inventory' where caption = 'DE03 - Recalculate inventory'
update batchjob set caption = 'RET: DE03 - Update employee discounts info subcodes' where caption = 'DE03 - Update employee discounts info subcodes'
update batchjob set caption = 'FIN: DK01 - Calculate statement' where caption = 'DK01 - Calculate statement'
update batchjob set caption = 'FIN: DK01 - IW Import invoices from READSOFT' where caption = 'DK01 - IW Import invoices from READSOFT'
update batchjob set caption = 'FIN: DK01 - Post statement' where caption = 'DK01 - Post statement'
update batchjob set caption = 'FIN: DK01 - Recalculate inventory' where caption = 'DK01 - Recalculate inventory'
update batchjob set caption = 'RET: DK01 - Update employee discounts info subcodes' where caption = 'DK01 - Update employee discounts info subcodes'
update batchjob set caption = 'SYS: E-mail distributor batch' where caption = 'E-mail distributor batch'
update batchjob set caption = 'PAR: Export barcodes to partners AT01' where caption = 'Export barcodes to partners AT01'
update batchjob set caption = 'PAR: Export barcodes to partners BE01' where caption = 'Export barcodes to partners BE01'
update batchjob set caption = 'PAR: Export barcodes to partners BE02' where caption = 'Export barcodes to partners BE02'
update batchjob set caption = 'PAR: Export barcodes to partners CH01' where caption = 'Export barcodes to partners CH01'
update batchjob set caption = 'PAR: Export barcodes to partners CY01' where caption = 'Export barcodes to partners CY01'
update batchjob set caption = 'PAR: Export barcodes to partners CZ01' where caption = 'Export barcodes to partners CZ01'
update batchjob set caption = 'PAR: Export barcodes to partners DE02' where caption = 'Export barcodes to partners DE02'
update batchjob set caption = 'PAR: Export barcodes to partners DE04' where caption = 'Export barcodes to partners DE04'
update batchjob set caption = 'PAR: Export barcodes to partners DE05' where caption = 'Export barcodes to partners DE05'
update batchjob set caption = 'PAR: Export barcodes to partners EE01 Estland' where caption = 'Export barcodes to partners EE01 Estland'
update batchjob set caption = 'PAR: Export barcodes to partners ES01' where caption = 'Export barcodes to partners ES01'
update batchjob set caption = 'PAR: Export barcodes to partners ES02' where caption = 'Export barcodes to partners ES02'
update batchjob set caption = 'PAR: Export barcodes to partners ES03' where caption = 'Export barcodes to partners ES03'
update batchjob set caption = 'PAR: Export barcodes to partners ES04' where caption = 'Export barcodes to partners ES04'
update batchjob set caption = 'PAR: Export barcodes to partners ES05' where caption = 'Export barcodes to partners ES05'
update batchjob set caption = 'PAR: Export barcodes to partners ES06' where caption = 'Export barcodes to partners ES06'
update batchjob set caption = 'PAR: Export barcodes to partners FO01' where caption = 'Export barcodes to partners FO01'
update batchjob set caption = 'PAR: Export barcodes to partners FR01' where caption = 'Export barcodes to partners FR01'
update batchjob set caption = 'PAR: Export barcodes to partners FR02' where caption = 'Export barcodes to partners FR02'
update batchjob set caption = 'PAR: Export barcodes to partners FR04' where caption = 'Export barcodes to partners FR04'
update batchjob set caption = 'PAR: Export barcodes to partners GB02' where caption = 'Export barcodes to partners GB02'
update batchjob set caption = 'PAR: Export barcodes to partners GB03' where caption = 'Export barcodes to partners GB03'
update batchjob set caption = 'PAR: Export barcodes to partners GB04' where caption = 'Export barcodes to partners GB04'
update batchjob set caption = 'PAR: Export barcodes to partners GB05 SC' where caption = 'Export barcodes to partners GB05 SC'
update batchjob set caption = 'PAR: Export barcodes to partners GB06 NI1' where caption = 'Export barcodes to partners GB06 NI1'
update batchjob set caption = 'PAR: Export barcodes to partners GR01' where caption = 'Export barcodes to partners GR01'
update batchjob set caption = 'PAR: Export barcodes to partners HU01' where caption = 'Export barcodes to partners HU01'
update batchjob set caption = 'PAR: Export barcodes to partners IE01' where caption = 'Export barcodes to partners IE01'
update batchjob set caption = 'PAR: Export barcodes to partners IT01' where caption = 'Export barcodes to partners IT01'
update batchjob set caption = 'PAR: Export barcodes to partners IT02' where caption = 'Export barcodes to partners IT02'
update batchjob set caption = 'PAR: Export barcodes to partners IT03' where caption = 'Export barcodes to partners IT03'
update batchjob set caption = 'PAR: Export barcodes to partners JP01' where caption = 'Export barcodes to partners JP01'
update batchjob set caption = 'PAR: Export barcodes to partners KR01' where caption = 'Export barcodes to partners KR01'
update batchjob set caption = 'PAR: Export barcodes to partners LT01 Litauen' where caption = 'Export barcodes to partners LT01 Litauen'
update batchjob set caption = 'PAR: Export barcodes to partners LV01 Letland' where caption = 'Export barcodes to partners LV01 Letland'
update batchjob set caption = 'PAR: Export barcodes to partners MT01' where caption = 'Export barcodes to partners MT01'
update batchjob set caption = 'PAR: Export barcodes to partners NL01' where caption = 'Export barcodes to partners NL01'
update batchjob set caption = 'PAR: Export barcodes to partners PL01' where caption = 'Export barcodes to partners PL01'
update batchjob set caption = 'PAR: Export barcodes to partners PL02' where caption = 'Export barcodes to partners PL02'
update batchjob set caption = 'PAR: Export barcodes to partners PT01' where caption = 'Export barcodes to partners PT01'
update batchjob set caption = 'PAR: Export items to partners AT01' where caption = 'Export items to partners AT01'
update batchjob set caption = 'PAR: Export items to partners BE01' where caption = 'Export items to partners BE01'
update batchjob set caption = 'PAR: Export items to partners BE02' where caption = 'Export items to partners BE02'
update batchjob set caption = 'PAR: Export items to partners CH01' where caption = 'Export items to partners CH01'
update batchjob set caption = 'PAR: Export items to partners CY01' where caption = 'Export items to partners CY01'
update batchjob set caption = 'PAR: Export items to partners CZ01' where caption = 'Export items to partners CZ01'
update batchjob set caption = 'PAR: Export items to partners DE02' where caption = 'Export items to partners DE02'
update batchjob set caption = 'PAR: Export items to partners DE04' where caption = 'Export items to partners DE04'
update batchjob set caption = 'PAR: Export items to partners DE05' where caption = 'Export items to partners DE05'
update batchjob set caption = 'PAR: Export items to partners EE01 Estland' where caption = 'Export items to partners EE01 Estland'
update batchjob set caption = 'PAR: Export items to partners ES01' where caption = 'Export items to partners ES01'
update batchjob set caption = 'PAR: Export items to partners ES02' where caption = 'Export items to partners ES02'
update batchjob set caption = 'PAR: Export items to partners ES03' where caption = 'Export items to partners ES03'
update batchjob set caption = 'PAR: Export items to partners ES04' where caption = 'Export items to partners ES04'
update batchjob set caption = 'PAR: Export items to partners ES05' where caption = 'Export items to partners ES05'
update batchjob set caption = 'PAR: Export items to partners ES06' where caption = 'Export items to partners ES06'
update batchjob set caption = 'PAR: Export items to partners FO01' where caption = 'Export items to partners FO01'
update batchjob set caption = 'PAR: Export items to partners FR01' where caption = 'Export items to partners FR01'
update batchjob set caption = 'PAR: Export items to partners FR02' where caption = 'Export items to partners FR02'
update batchjob set caption = 'PAR: Export items to partners FR04' where caption = 'Export items to partners FR04'
update batchjob set caption = 'PAR: Export items to partners GB01 And Barcodes' where caption = 'Export items to partners GB01 And Barcodes'
update batchjob set caption = 'PAR: Export items to partners GB02' where caption = 'Export items to partners GB02'
update batchjob set caption = 'PAR: Export items to partners GB03' where caption = 'Export items to partners GB03'
update batchjob set caption = 'PAR: Export items to partners GB04' where caption = 'Export items to partners GB04'
update batchjob set caption = 'PAR: Export items to partners GB05 SC' where caption = 'Export items to partners GB05 SC'
update batchjob set caption = 'PAR: Export items to partners GB06 NI' where caption = 'Export items to partners GB06 NI'
update batchjob set caption = 'PAR: Export items to partners GR01' where caption = 'Export items to partners GR01'
update batchjob set caption = 'PAR: Export items to partners HU01' where caption = 'Export items to partners HU01'
update batchjob set caption = 'PAR: Export items to partners IE01' where caption = 'Export items to partners IE01'
update batchjob set caption = 'PAR: Export items to partners IT01' where caption = 'Export items to partners IT01'
update batchjob set caption = 'PAR: Export items to partners IT02' where caption = 'Export items to partners IT02'
update batchjob set caption = 'PAR: Export items to partners IT03' where caption = 'Export items to partners IT03'
update batchjob set caption = 'PAR: Export items to partners JP01' where caption = 'Export items to partners JP01'
update batchjob set caption = 'PAR: Export items to partners KR01' where caption = 'Export items to partners KR01'
update batchjob set caption = 'PAR: Export items to partners LT01 Litauen' where caption = 'Export items to partners LT01 Litauen'
update batchjob set caption = 'PAR: Export items to partners LV01 Letland' where caption = 'Export items to partners LV01 Letland'
update batchjob set caption = 'PAR: Export items to partners MT01' where caption = 'Export items to partners MT01'
update batchjob set caption = 'PAR: Export items to partners NL01' where caption = 'Export items to partners NL01'
update batchjob set caption = 'PAR: Export items to partners PL01' where caption = 'Export items to partners PL01'
update batchjob set caption = 'PAR: Export items to partners PL02' where caption = 'Export items to partners PL02'
update batchjob set caption = 'PAR: Export items to partners PT01' where caption = 'Export items to partners PT01'
update batchjob set caption = 'PAR: Export sales invoices to partners AT01' where caption = 'Export sales invoices to partners AT01'
update batchjob set caption = 'PAR: Export sales invoices to partners AX DE01' where caption = 'Export sales invoices to partners AX DE01'
update batchjob set caption = 'PAR: Export sales invoices to partners AX DE03' where caption = 'Export sales invoices to partners AX DE03'
update batchjob set caption = 'PAR: Export sales invoices to partners AX DK01' where caption = 'Export sales invoices to partners AX DK01'
update batchjob set caption = 'PAR: Export sales invoices to partners AX FI01' where caption = 'Export sales invoices to partners AX FI01'
update batchjob set caption = 'PAR: Export sales invoices to partners AX IS01' where caption = 'Export sales invoices to partners AX IS01'
update batchjob set caption = 'PAR: Export sales invoices to partners AX NO01' where caption = 'Export sales invoices to partners AX NO01'
update batchjob set caption = 'PAR: Export sales invoices to partners AX SE01' where caption = 'Export sales invoices to partners AX SE01'
update batchjob set caption = 'PAR: Export sales invoices to partners AX SE02' where caption = 'Export sales invoices to partners AX SE02'
update batchjob set caption = 'PAR: Export sales invoices to partners AX SK01' where caption = 'Export sales invoices to partners AX SK01'
update batchjob set caption = 'PAR: Export sales invoices to partners AX US01' where caption = 'Export sales invoices to partners AX US01'
update batchjob set caption = 'PAR: Export sales invoices to partners BE01' where caption = 'Export sales invoices to partners BE01'
update batchjob set caption = 'PAR: Export sales invoices to partners BE02' where caption = 'Export sales invoices to partners BE02'
update batchjob set caption = 'PAR: Export sales invoices to partners CH01' where caption = 'Export sales invoices to partners CH01'
update batchjob set caption = 'PAR: Export sales invoices to partners CY01' where caption = 'Export sales invoices to partners CY01'
update batchjob set caption = 'PAR: Export sales invoices to partners CZ01' where caption = 'Export sales invoices to partners CZ01'
update batchjob set caption = 'PAR: Export sales invoices to partners DE01' where caption = 'Export sales invoices to partners DE01'
update batchjob set caption = 'PAR: Export sales invoices to partners DE02' where caption = 'Export sales invoices to partners DE02'
update batchjob set caption = 'PAR: Export sales invoices to partners DE04' where caption = 'Export sales invoices to partners DE04'
update batchjob set caption = 'PAR: Export sales invoices to partners DE05' where caption = 'Export sales invoices to partners DE05'
update batchjob set caption = 'PAR: Export sales invoices to partners EE01 Estland' where caption = 'Export sales invoices to partners EE01 Estland'
update batchjob set caption = 'PAR: Export sales invoices to partners ES01' where caption = 'Export sales invoices to partners ES01'
update batchjob set caption = 'PAR: Export sales invoices to partners ES02' where caption = 'Export sales invoices to partners ES02'
update batchjob set caption = 'PAR: Export sales invoices to partners ES03' where caption = 'Export sales invoices to partners ES03'
update batchjob set caption = 'PAR: Export sales invoices to partners ES04' where caption = 'Export sales invoices to partners ES04'
update batchjob set caption = 'PAR: Export sales invoices to partners ES05' where caption = 'Export sales invoices to partners ES05'
update batchjob set caption = 'PAR: Export sales invoices to partners ES06' where caption = 'Export sales invoices to partners ES06'
update batchjob set caption = 'PAR: Export sales invoices to partners FO01' where caption = 'Export sales invoices to partners FO01'
update batchjob set caption = 'PAR: Export sales invoices to partners FR01' where caption = 'Export sales invoices to partners FR01'
update batchjob set caption = 'PAR: Export sales invoices to partners FR02' where caption = 'Export sales invoices to partners FR02'
update batchjob set caption = 'PAR: Export sales invoices to partners FR04' where caption = 'Export sales invoices to partners FR04'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01002' where caption = 'Export sales invoices to partners GB01002'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01003' where caption = 'Export sales invoices to partners GB01003'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01004' where caption = 'Export sales invoices to partners GB01004'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01005' where caption = 'Export sales invoices to partners GB01005'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01006' where caption = 'Export sales invoices to partners GB01006'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01007' where caption = 'Export sales invoices to partners GB01007'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01008' where caption = 'Export sales invoices to partners GB01008'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01009' where caption = 'Export sales invoices to partners GB01009'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01011' where caption = 'Export sales invoices to partners GB01011'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01013' where caption = 'Export sales invoices to partners GB01013'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01014' where caption = 'Export sales invoices to partners GB01014'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01015' where caption = 'Export sales invoices to partners GB01015'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01016' where caption = 'Export sales invoices to partners GB01016'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01017' where caption = 'Export sales invoices to partners GB01017'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01018' where caption = 'Export sales invoices to partners GB01018'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01019' where caption = 'Export sales invoices to partners GB01019'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01020' where caption = 'Export sales invoices to partners GB01020'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01021' where caption = 'Export sales invoices to partners GB01021'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01022' where caption = 'Export sales invoices to partners GB01022'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01023' where caption = 'Export sales invoices to partners GB01023'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01024' where caption = 'Export sales invoices to partners GB01024'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01025' where caption = 'Export sales invoices to partners GB01025'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01026' where caption = 'Export sales invoices to partners GB01026'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01027' where caption = 'Export sales invoices to partners GB01027'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01028' where caption = 'Export sales invoices to partners GB01028'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01029' where caption = 'Export sales invoices to partners GB01029'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01030' where caption = 'Export sales invoices to partners GB01030'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01031' where caption = 'Export sales invoices to partners GB01031'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01032' where caption = 'Export sales invoices to partners GB01032'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01033' where caption = 'Export sales invoices to partners GB01033'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01034' where caption = 'Export sales invoices to partners GB01034'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01035' where caption = 'Export sales invoices to partners GB01035'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01036' where caption = 'Export sales invoices to partners GB01036'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01037' where caption = 'Export sales invoices to partners GB01037'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01038' where caption = 'Export sales invoices to partners GB01038'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01039' where caption = 'Export sales invoices to partners GB01039'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01040' where caption = 'Export sales invoices to partners GB01040'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01041' where caption = 'Export sales invoices to partners GB01041'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01042' where caption = 'Export sales invoices to partners GB01042'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01043' where caption = 'Export sales invoices to partners GB01043'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01044' where caption = 'Export sales invoices to partners GB01044'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01045' where caption = 'Export sales invoices to partners GB01045'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01046' where caption = 'Export sales invoices to partners GB01046'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01047' where caption = 'Export sales invoices to partners GB01047'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01048' where caption = 'Export sales invoices to partners GB01048'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01049' where caption = 'Export sales invoices to partners GB01049'
update batchjob set caption = 'PAR: Export sales invoices to partners GB01052' where caption = 'Export sales invoices to partners GB01052'
update batchjob set caption = 'PAR: Export sales invoices to partners GB02' where caption = 'Export sales invoices to partners GB02'
update batchjob set caption = 'PAR: Export sales invoices to partners GB03' where caption = 'Export sales invoices to partners GB03'
update batchjob set caption = 'PAR: Export sales invoices to partners GB04' where caption = 'Export sales invoices to partners GB04'
update batchjob set caption = 'PAR: Export sales invoices to partners GB05 SC' where caption = 'Export sales invoices to partners GB05 SC'
update batchjob set caption = 'PAR: Export sales invoices to partners GB06 NI' where caption = 'Export sales invoices to partners GB06 NI'
update batchjob set caption = 'PAR: Export sales invoices to partners GR01' where caption = 'Export sales invoices to partners GR01'
update batchjob set caption = 'PAR: Export sales invoices to partners HU01001' where caption = 'Export sales invoices to partners HU01001'
update batchjob set caption = 'PAR: Export sales invoices to partners HU01002' where caption = 'Export sales invoices to partners HU01002'
update batchjob set caption = 'PAR: Export sales invoices to partners HU01003' where caption = 'Export sales invoices to partners HU01003'
update batchjob set caption = 'PAR: Export sales invoices to partners HU01004' where caption = 'Export sales invoices to partners HU01004'
update batchjob set caption = 'PAR: Export sales invoices to partners HU01006' where caption = 'Export sales invoices to partners HU01006'
update batchjob set caption = 'PAR: Export sales invoices to partners IE01' where caption = 'Export sales invoices to partners IE01'
update batchjob set caption = 'PAR: Export sales invoices to partners IT01' where caption = 'Export sales invoices to partners IT01'
update batchjob set caption = 'PAR: Export sales invoices to partners IT02' where caption = 'Export sales invoices to partners IT02'
update batchjob set caption = 'PAR: Export sales invoices to partners IT03' where caption = 'Export sales invoices to partners IT03'
update batchjob set caption = 'PAR: Export sales invoices to partners JP01' where caption = 'Export sales invoices to partners JP01'
update batchjob set caption = 'PAR: Export sales invoices to partners KR01' where caption = 'Export sales invoices to partners KR01'
update batchjob set caption = 'PAR: Export sales invoices to partners LT01 Litauen' where caption = 'Export sales invoices to partners LT01 Litauen'
update batchjob set caption = 'PAR: Export sales invoices to partners LV01 Letland' where caption = 'Export sales invoices to partners LV01 Letland'
update batchjob set caption = 'PAR: Export sales invoices to partners MT01' where caption = 'Export sales invoices to partners MT01'
update batchjob set caption = 'PAR: Export sales invoices to partners NL01' where caption = 'Export sales invoices to partners NL01'
update batchjob set caption = 'PAR: Export sales invoices to partners PL01' where caption = 'Export sales invoices to partners PL01'
update batchjob set caption = 'PAR: Export sales invoices to partners PL02' where caption = 'Export sales invoices to partners PL02'
update batchjob set caption = 'PAR: Export sales invoices to partners PT01' where caption = 'Export sales invoices to partners PT01'
update batchjob set caption = 'PAR: Export sales to partners GB02' where caption = 'Export sales to partners GB02'
update batchjob set caption = 'PAR: Export sales to partners GB03' where caption = 'Export sales to partners GB03'
update batchjob set caption = 'PAR: Export sales to partners GB04' where caption = 'Export sales to partners GB04'
update batchjob set caption = 'PAR: Export sales to partners GB05 SC' where caption = 'Export sales to partners GB05 SC'
update batchjob set caption = 'PAR: Export sales to partners GB06 NI' where caption = 'Export sales to partners GB06 NI'
update batchjob set caption = 'FIN: FI01 - Calculate statement' where caption = 'FI01 - Calculate statement'
update batchjob set caption = 'FIN: FI01 - Post statement' where caption = 'FI01 - Post statement'
update batchjob set caption = 'FIN: FI01 - Recalculate inventory' where caption = 'FI01 - Recalculate inventory'
update batchjob set caption = 'RET: FI01 - Update employee discounts info subcodes' where caption = 'FI01 - Update employee discounts info subcodes'
update batchjob set caption = 'FIN: Customer aging snapshot GROUP' where caption = 'FIN - Customer aging snapshot GROUP'
update batchjob set caption = 'FIN: Calculate estimated landed cost' where caption = 'FIN Calculate estimated landed cost'
update batchjob set caption = 'FIN: Sales order invoice - Internal /donations ' where caption = 'FIN: Internal /donations orders invoice'
update batchjob set caption = 'FIN: Sales order invoice - APAC' where caption = 'FIN: Order invoice - APAC'
update batchjob set caption = 'FIN: Sales order invoice - daily' where caption = 'FIN: Order invoice - daily'
update batchjob set caption = 'FIN: Sales order invoice - hourly' where caption = 'FIN: Order invoice - hourly'
update batchjob set caption = 'SYS: General batch monitoring' where caption = 'General batch monitoring'
update batchjob set caption = 'RET: Fix exchange rates for gift card payments' where caption = 'Global - Fix exchange rates for gift card payments'
update batchjob set caption = 'RET: HT Process Scanned Lines' where caption = 'HT Process Scanned Lines'
update batchjob set caption = 'RET: IS01 - Update employee discounts info subcodes' where caption = 'IS01 -    Update employee discounts info subcodes'
update batchjob set caption = 'FIN: IS01 - Calculate statement' where caption = 'IS01 - Calculate statement'
update batchjob set caption = 'FIN: IS01 - Export vendor data to Readsoft Online' where caption = 'IS01 - Export vendor data to Readsoft Online'
update batchjob set caption = 'FIN: IS01 - Import invoices from XML' where caption = 'IS01 - Import invoices from XML'
update batchjob set caption = 'FIN: IS01 - Post statement' where caption = 'IS01 - Post statement'
update batchjob set caption = 'FIN: IS01 - Recalculate inventory' where caption = 'IS01 - Recalculate inventory'
update batchjob set caption = 'SYS: Lasernet tasks' where caption = 'Lasernet tasks'
update batchjob set caption = 'LOG: Blue Water' where caption = 'LOG: Blue Water'
update batchjob set caption = 'LOG: Generate SO pick-list for WMS released' where caption = 'LOG: Generate SO pick-list for WMS released'
update batchjob set caption = 'LOG: Hecksher, receive booking' where caption = 'LOG: Hecksher, receive booking'
update batchjob set caption = 'LOG: Inbound (Type-3, Type-32) - FILE' where caption = 'LOG: Inbound (Type-3, Type-32) - FILE'
update batchjob set caption = 'LOG: Inbound (Type-3, Type-32) - MSMQ' where caption = 'LOG: Inbound (Type-3, Type-32) - MSMQ'
update batchjob set caption = 'LOG: Order packing slip (15/min)' where caption = 'LOG: Order packing slip (15/min)'
update batchjob set caption = 'LOG: Order packing slip (Hourly)' where caption = 'LOG: Order packing slip (Hourly)'
update batchjob set caption = 'LOG: Outbound (Type-4, Type-42) - FILE' where caption = 'LOG: Outbound (Type-4, Type-42) - FILE'
update batchjob set caption = 'LOG: Outbound (Type-4, Type-42) - MSMQ' where caption = 'LOG: Outbound (Type-4, Type-42) - MSMQ'
update batchjob set caption = 'LOG: Receive WMS messages - FILE' where caption = 'LOG: Receive WMS messages - FILE'
update batchjob set caption = 'LOG: Receive WMS messages - MSMQ' where caption = 'LOG: Receive WMS messages - MSMQ'
update batchjob set caption = 'LOG: Type-1 – Product master data (2000/Sunday)' where caption = 'LOG: Type-1 – Product master data (2000/Sunday)'
update batchjob set caption = 'LOG: Type-1 – Product master data (250/night)' where caption = 'LOG: Type-1 – Product master data (250/night)'
update batchjob set caption = 'LOG: Update integration log search table' where caption = 'LOG: Update integration log search table'
update batchjob set caption = 'LOG: Weeks on hand' where caption = 'LOG: Weeks on hand'
update batchjob set caption = 'LOG: WMS log retry processing' where caption = 'LOG: WMS log retry processing'
update batchjob set caption = 'FIN: NO01 - Calculate statement' where caption = 'NO01 - Calculate statement'
update batchjob set caption = 'FIN: NO01 - Post statement' where caption = 'NO01 - Post statement'
update batchjob set caption = 'FIN: NO01 - Recalculate inventory' where caption = 'NO01 - Recalculate inventory'
update batchjob set caption = 'RET: NO01 - Update employee discounts info subcodes' where caption = 'NO01 - Update employee discounts info subcodes'
update batchjob set caption = 'RET: Post inventory GROUP' where caption = 'RET - Post inventory GROUP'
update batchjob set caption = 'RET: Assortment job GROUP' where caption = 'RET - Retail assortment job GROUP'
update batchjob set caption = 'RET: RetailAll Customer' where caption = 'RetailAll Customer'
update batchjob set caption = 'RET: RetailAll Daily UTC+0' where caption = 'RetailAll Daily UTC+0'
update batchjob set caption = 'RET: RetailAll Daily UTC+1' where caption = 'RetailAll Daily UTC+1'
update batchjob set caption = 'RET: RetailAll Daily UTC-6' where caption = 'RetailAll Daily UTC-6'
update batchjob set caption = 'RET: RetailAll Process status messages' where caption = 'RetailAll Process status messages'
update batchjob set caption = 'RET: RetailAll Purchase Order Import' where caption = 'RetailAll Purchase Order Import'
update batchjob set caption = 'RET: RetailAll Staff' where caption = 'RetailAll Staff'
update batchjob set caption = 'RET: RetailAll Transactions' where caption = 'RetailAll Transactions'
update batchjob set caption = 'FIN: SE01 - Calculate statement' where caption = 'SE01 - Calculate statement'
update batchjob set caption = 'FIN: SE01 - Import invoices from XML' where caption = 'SE01 - Import invoices from XML'
update batchjob set caption = 'FIN: SE01 - Post statement' where caption = 'SE01 - Post statement'
update batchjob set caption = 'FIN: SE01 - Recalculate inventory' where caption = 'SE01 - Recalculate inventory'
update batchjob set caption = 'RET: SE01 - Update employee discounts info subcodes' where caption = 'SE01 - Update employee discounts info subcodes'
update batchjob set caption = 'FIN: SE02 - Calculate statement' where caption = 'SE02 - Calculate statement'
update batchjob set caption = 'FIN: SE02 - Export vendor data to Readsoft Online' where caption = 'SE02 - Export vendor data to Readsoft Online'
update batchjob set caption = 'FIN: SE02 - Import invoices from XML' where caption = 'SE02 - Import invoices from XML'
update batchjob set caption = 'FIN: SE02 - Post statement' where caption = 'SE02 - Post statement'
update batchjob set caption = 'FIN: SE02 - Recalculate inventory' where caption = 'SE02 - Recalculate inventory'
update batchjob set caption = 'RET: SE02 - Update employee discounts info subcodes' where caption = 'SE02 - Update employee discounts info subcodes'
update batchjob set caption = 'FIN: SK01 - Calculate statement' where caption = 'SK01 - Calculate statement'
update batchjob set caption = 'FIN: SK01 - Post statement' where caption = 'SK01 - Post statement'
update batchjob set caption = 'FIN: SK01 - Recalculate inventory' where caption = 'SK01 - Recalculate inventory'
update batchjob set caption = 'SOP: Create sales order (committed campaigns, 5 min job)' where caption = 'SOP: Create sales order (committed campaigns, 5 min job)'
update batchjob set caption = 'SOP: Create sales order (not campaign, 2 min job)' where caption = 'SOP: Create sales order (not campaign, 2 min job)'
update batchjob set caption = 'SOP: Create sales order (not campaign, 5 min job)' where caption = 'SOP: Create sales order (not campaign, 5 min job)'
update batchjob set caption = 'SOP: Generate Access User Groups to file' where caption = 'SOP: Generate Access User Groups to file'
update batchjob set caption = 'SYS: Change based alerts' where caption = 'SYS Change based alerts'
update batchjob set caption = 'SYS: Retail discovery batch job' where caption = 'SYS Retail discovery batch job'
update batchjob set caption = 'FIN: US01 - Calculate statement' where caption = 'US01 - Calculate statement'
update batchjob set caption = 'FIN: US01 - Export vendor data to Readsoft Online' where caption = 'US01 - Export vendor data to Readsoft Online'
update batchjob set caption = 'FIN: US01 - Import invoices from XML' where caption = 'US01 - Import invoices from XML'
update batchjob set caption = 'FIN: US01 - Post statement' where caption = 'US01 - Post statement'
update batchjob set caption = 'FIN: US01 - Recalculate inventory' where caption = 'US01 - Recalculate inventory'
update batchjob set caption = 'RET: US01 - Update employee discounts info subcodes' where caption = 'US01 - Update employee discounts info subcodes'
update batchjob set caption = 'SYS: Workflow due date processing' where caption = 'Workflow due date processing'
update batchjob set caption = 'SYS: Workflow line-item notifications' where caption = 'Workflow line-item notifications'
update batchjob set caption = 'SYS: Workflow message processing' where caption = 'Workflow message processing'
update batchjob set caption = 'FIN: ZEAS - Export vendor data to Readsoft Online' where caption = 'ZEAS - Export vendor data to Readsoft Online'
update batchjob set caption = 'FIN: ZEAS - Import currency exchange rates from Danish National Bank' where caption = 'ZEAS - Import currency exchange rates from Danish National Bank'
update batchjob set caption = 'FIN: ZEAS - Import invoices from READSOFT' where caption = 'ZEAS - Import invoices from READSOFT'
update batchjob set caption = 'FIN: ZEAS - IW e-mail Redirected invoices' where caption = 'ZEAS - IW e-mail Redirected invoices'
update batchjob set caption = 'FIN: ZEAS - IW e-mail Reminder/escalation' where caption = 'ZEAS - IW e-mail Reminder/escalation'
update batchjob set caption = 'FIN: ZEAS - IW e-mail Send batch mails originating from MW-Workflow' where caption = 'ZEAS - IW e-mail Send batch mails originating from MW-Workflow'
update batchjob set caption = 'FIN: ZEAS - IW invoice register, Auto approval and posting - PO' where caption = 'ZEAS - IW invoice register, Auto approval and posting - PO'
update batchjob set caption = 'FIN: ZEAS - Update charge group on vendors and items' where caption = 'ZEAS - Update charge group on vendors and items'
update batchjob set caption = 'FIN: ZEAS - Reminder IWF Invoices' where caption = 'ZEAS -Reminder IWF Invoices'


update batch set caption = 'FIN: 1. ZEAS - IW invoice register' where caption = '1. ZEAS - IW invoice register'
update batch set caption = 'FIN: 2. ZEAS - IW Automatic purchase invoice approval and posting' where caption = '2. ZEAS - IW Automatic purchase invoice approval and posting'
update batch set caption = 'FIN: 3. ZEAS - IW Automatic approved matching invoices' where caption = '3. ZEAS - IW Automatic approved matching invoices'
update batch set caption = 'FIN: ALL - Import bank return files from AMC' where caption = 'ALL - Import bank return files from AMC'
update batch set caption = 'COM: Partner Price changes' where caption = 'ALL - Partner Price changes'
update batch set caption = 'RET: AT01 - Retail assortments job' where caption = 'AT01 - Retail assortments job'
update batch set caption = 'SYS: Automatic role assignment' where caption = 'Automatic role assignment'
update batch set caption = 'SYS: Batch monitoring' where caption = 'Batch monitoring'
update batch set caption = 'RET: BE01 - Retail assortments job' where caption = 'BE01 - Retail assortments job'
update batch set caption = 'RET: BE02 - Retail assortments job' where caption = 'BE02 - Retail assortments job'
update batch set caption = 'RET: CH01 - Retail assortments job' where caption = 'CH01 - Retail assortments job'
update batch set caption = 'COM: Import item pictures' where caption = 'COM Import item pictures'
update batch set caption = 'COM: Update item tax groups on item ALL' where caption = 'COM Update item tax groups on item ALL'
update batch set caption = 'RET: CY01 - Retail assortments job' where caption = 'CY01 - Retail assortments job'
update batch set caption = 'RET: CZ01 - Retail assortments job' where caption = 'CZ01 - Retail assortments job'
update batch set caption = 'FIN: DE01 - Calculate statement' where caption = 'DE01 - Calculate statement'
update batch set caption = 'FIN: DE01 - Customer aging snapshot' where caption = 'DE01 - Customer aging snapshot'
update batch set caption = 'RET: DE01 - Post inventory' where caption = 'DE01 - Post inventory'
update batch set caption = 'FIN: DE01 - Post statement' where caption = 'DE01 - Post statement'
update batch set caption = 'FIN: DE01 - Recalculate inventory' where caption = 'DE01 - Recalculate inventory'
update batch set caption = 'RET: DE01 - Retail assortments job' where caption = 'DE01 - Retail assortments job'
update batch set caption = 'RET: DE01 - Update employee discounts info subcodes' where caption = 'DE01 - Update employee discounts info subcodes'
update batch set caption = 'RET: DE02 - Retail assortments job' where caption = 'DE02 - Retail assortments job'
update batch set caption = 'FIN: DE03 - Calculate statement' where caption = 'DE03 - Calculate statement'
update batch set caption = 'FIN: DE03 - Customer aging snapshot' where caption = 'DE03 - Customer aging snapshot'
update batch set caption = 'RET: DE03 - Post inventory' where caption = 'DE03 - Post inventory'
update batch set caption = 'FIN: DE03 - Post statement' where caption = 'DE03 - Post statement'
update batch set caption = 'FIN: DE03 - Recalculate inventory' where caption = 'DE03 - Recalculate inventory'
update batch set caption = 'RET: DE03 - Retail assortments job' where caption = 'DE03 - Retail assortments job'
update batch set caption = 'RET: DE03 - Update employee discounts info subcodes' where caption = 'DE03 - Update employee discounts info subcodes'
update batch set caption = 'RET: DE04 - Retail assortments job' where caption = 'DE04 - Retail assortments job'
update batch set caption = 'RET: DE05 - Retail assortments job' where caption = 'DE05 - Retail assortments job'
update batch set caption = 'FIN: DK01 - Calculate statement' where caption = 'DK01 - Calculate statement'
update batch set caption = 'FIN: DK01 - Customer aging snapshot' where caption = 'DK01 - Customer aging snapshot'
update batch set caption = 'FIN: DK01 - IW Import invoices from READSOFT' where caption = 'DK01 - IW Import invoices from READSOFT'
update batch set caption = 'RET: DK01 - Post inventory' where caption = 'DK01 - Post inventory'
update batch set caption = 'FIN: DK01 - Post statement' where caption = 'DK01 - Post statement'
update batch set caption = 'FIN: DK01 - Recalculate inventory' where caption = 'DK01 - Recalculate inventory'
update batch set caption = 'RET: DK01 - Retail assortments job' where caption = 'DK01 - Retail assortments job'
update batch set caption = 'RET: DK01 - Update employee discounts info subcodes' where caption = 'DK01 Update employee discounts info subcodes'
update batch set caption = 'RET: EE01 - Retail assortments job' where caption = 'EE01 - Retail assortments job'
update batch set caption = 'SYS: E-mail distributor batch' where caption = 'E-mail distributor batch'
update batch set caption = 'RET: ES02 - Retail assortments job' where caption = 'ES - Retail assortments job'
update batch set caption = 'RET: ES03 - Retail assortments job' where caption = 'ES03 - Retail assortments job'
update batch set caption = 'RET: ES04 - Retail assortments job' where caption = 'ES04 - Retail assortments job'
update batch set caption = 'RET: ES05 - Retail assortments job' where caption = 'ES05 - Retail assortments job'
update batch set caption = 'RET: ES06 - Retail assortments job' where caption = 'ES06 - Retail assortments job'
update batch set caption = 'PAR: Export barcodes to partners  BE01' where caption = 'Export barcodes to partners  BE01'
update batch set caption = 'PAR: Export barcodes to partners  BE02' where caption = 'Export barcodes to partners  BE02'
update batch set caption = 'PAR: Export barcodes to partners  CH01' where caption = 'Export barcodes to partners  CH01'
update batch set caption = 'PAR: Export barcodes to partners  ES03' where caption = 'Export barcodes to partners  ES03'
update batch set caption = 'PAR: Export barcodes to partners AT01' where caption = 'Export barcodes to partners AT01'
update batch set caption = 'PAR: Export barcodes to partners CY01' where caption = 'Export barcodes to partners CY01'
update batch set caption = 'PAR: Export barcodes to partners CZ01' where caption = 'Export barcodes to partners CZ01'
update batch set caption = 'PAR: Export barcodes to partners DE02' where caption = 'Export barcodes to partners DE02'
update batch set caption = 'PAR: Export barcodes to partners DE04' where caption = 'Export barcodes to partners DE04'
update batch set caption = 'PAR: Export barcodes to partners DE05' where caption = 'Export barcodes to partners DE05'
update batch set caption = 'PAR: Export barcodes to partners EE01 Estland' where caption = 'Export barcodes to partners EE01 Estland'
update batch set caption = 'PAR: Export barcodes to partners ES01' where caption = 'Export barcodes to partners ES01'
update batch set caption = 'PAR: Export barcodes to partners ES02' where caption = 'Export barcodes to partners ES02'
update batch set caption = 'PAR: Export barcodes to partners ES04' where caption = 'Export barcodes to partners ES04'
update batch set caption = 'PAR: Export barcodes to partners ES05' where caption = 'Export barcodes to partners ES05'
update batch set caption = 'PAR: Export barcodes to partners ES06' where caption = 'Export barcodes to partners ES06'
update batch set caption = 'PAR: Export barcodes to partners FO01' where caption = 'Export barcodes to partners FO01'
update batch set caption = 'PAR: Export barcodes to partners FR01' where caption = 'Export barcodes to partners FR01'
update batch set caption = 'PAR: Export barcodes to partners FR02' where caption = 'Export barcodes to partners FR02'
update batch set caption = 'PAR: Export barcodes to partners FR04' where caption = 'Export barcodes to partners FR04'
update batch set caption = 'PAR: Export barcodes to partners GB02' where caption = 'Export barcodes to partners GB02'
update batch set caption = 'PAR: Export barcodes to partners GB03' where caption = 'Export barcodes to partners GB03'
update batch set caption = 'PAR: Export barcodes to partners GB04' where caption = 'Export barcodes to partners GB04'
update batch set caption = 'PAR: Export barcodes to partners GB05 SC' where caption = 'Export barcodes to partners GB05 SC'
update batch set caption = 'PAR: Export barcodes to partners GB06 NI1' where caption = 'Export barcodes to partners GB06 NI1'
update batch set caption = 'PAR: Export barcodes to partners GR01' where caption = 'Export barcodes to partners GR01'
update batch set caption = 'PAR: Export barcodes to partners HU01001' where caption = 'Export barcodes to partners HU01001'
update batch set caption = 'PAR: Export barcodes to partners IE01' where caption = 'Export barcodes to partners IE01'
update batch set caption = 'PAR: Export barcodes to partners IT01' where caption = 'Export barcodes to partners IT01'
update batch set caption = 'PAR: Export barcodes to partners IT02' where caption = 'Export barcodes to partners IT02'
update batch set caption = 'PAR: Export barcodes to partners IT03' where caption = 'Export barcodes to partners IT03'
update batch set caption = 'PAR: Export barcodes to partners JP01' where caption = 'Export barcodes to partners JP01'
update batch set caption = 'PAR: Export barcodes to partners KR01' where caption = 'Export barcodes to partners KR01'
update batch set caption = 'PAR: Export barcodes to partners LT01 Litauen' where caption = 'Export barcodes to partners LT01 Litauen'
update batch set caption = 'PAR: Export barcodes to partners LV01 Letland' where caption = 'Export barcodes to partners LV01 Letland'
update batch set caption = 'PAR: Export barcodes to partners MT01' where caption = 'Export barcodes to partners MT01'
update batch set caption = 'PAR: Export barcodes to partners NL01' where caption = 'Export barcodes to partners NL01'
update batch set caption = 'PAR: Export barcodes to partners PL01' where caption = 'Export barcodes to partners PL01'
update batch set caption = 'PAR: Export barcodes to partners PL02' where caption = 'Export barcodes to partners PL02'
update batch set caption = 'PAR: Export barcodes to partners PT01' where caption = 'Export barcodes to partners PT01'
update batch set caption = 'PAR: Export items to partners' where caption = 'Export items to partners'
update batch set caption = 'PAR: Export items to partners AT01' where caption = 'Export items to partners AT01'
update batch set caption = 'PAR: Export items to partners BE01' where caption = 'Export items to partners BE01'
update batch set caption = 'PAR: Export items to partners BE02' where caption = 'Export items to partners BE02'
update batch set caption = 'PAR: Export items to partners CH01' where caption = 'Export items to partners CH01'
update batch set caption = 'PAR: Export items to partners CY01' where caption = 'Export items to partners CY01'
update batch set caption = 'PAR: Export items to partners CZ01' where caption = 'Export items to partners CZ01'
update batch set caption = 'PAR: Export items to partners DE02' where caption = 'Export items to partners DE02'
update batch set caption = 'PAR: Export items to partners DE04' where caption = 'Export items to partners DE04'
update batch set caption = 'PAR: Export items to partners DE05' where caption = 'Export items to partners DE05'
update batch set caption = 'PAR: Export items to partners EE01' where caption = 'Export items to partners EE01'
update batch set caption = 'PAR: Export items to partners ES01' where caption = 'Export items to partners ES01'
update batch set caption = 'PAR: Export items to partners ES02' where caption = 'Export items to partners ES02'
update batch set caption = 'PAR: Export items to partners ES03' where caption = 'Export items to partners ES03'
update batch set caption = 'PAR: Export items to partners ES04' where caption = 'Export items to partners ES04'
update batch set caption = 'PAR: Export items to partners ES05' where caption = 'Export items to partners ES05'
update batch set caption = 'PAR: Export items to partners ES06' where caption = 'Export items to partners ES06'
update batch set caption = 'PAR: Export items to partners FO01' where caption = 'Export items to partners FO01'
update batch set caption = 'PAR: Export items to partners FR01' where caption = 'Export items to partners FR01'
update batch set caption = 'PAR: Export items to partners FR02' where caption = 'Export items to partners FR02'
update batch set caption = 'PAR: Export items to partners FR04' where caption = 'Export items to partners FR04'
update batch set caption = 'PAR: Export items to partners GB02' where caption = 'Export items to partners GB02'
update batch set caption = 'PAR: Export items to partners GB03' where caption = 'Export items to partners GB03'
update batch set caption = 'PAR: Export items to partners GB04' where caption = 'Export items to partners GB04'
update batch set caption = 'PAR: Export items to partners GB05 SC' where caption = 'Export items to partners GB05 SC'
update batch set caption = 'PAR: Export items to partners GB06  NI' where caption = 'Export items to partners GB06  NI'
update batch set caption = 'PAR: Export items to partners GR01 EUR' where caption = 'Export items to partners GR01 EUR'
update batch set caption = 'PAR: Export items to partners HU01' where caption = 'Export items to partners HU01'
update batch set caption = 'PAR: Export items to partners IE01 EUR' where caption = 'Export items to partners IE01 EUR'
update batch set caption = 'PAR: Export items to partners IT01 EUR' where caption = 'Export items to partners IT01 EUR'
update batch set caption = 'PAR: Export items to partners IT02 EUR' where caption = 'Export items to partners IT02 EUR'
update batch set caption = 'PAR: Export items to partners IT03' where caption = 'Export items to partners IT03'
update batch set caption = 'PAR: Export items to partners JP01' where caption = 'Export items to partners JP01'
update batch set caption = 'PAR: Export items to partners KR01 EUR' where caption = 'Export items to partners KR01 EUR'
update batch set caption = 'PAR: Export items to partners LT01 Litauen' where caption = 'Export items to partners LT01 Litauen'
update batch set caption = 'PAR: Export items to partners LV01 Letland' where caption = 'Export items to partners LV01 Letland'
update batch set caption = 'PAR: Export items to partners MT01' where caption = 'Export items to partners MT01'
update batch set caption = 'PAR: Export items to partners NL01 EUR' where caption = 'Export items to partners NL01 EUR'
update batch set caption = 'PAR: Export items to partners PL01' where caption = 'Export items to partners PL01'
update batch set caption = 'PAR: Export items to partners PL02' where caption = 'Export items to partners PL02'
update batch set caption = 'PAR: Export items to partners PT01 EUR' where caption = 'Export items to partners PT01 EUR'
update batch set caption = 'PAR: Export sales invoices to partners  AX FI01' where caption = 'Export sales invoices to partners  AX FI01'
update batch set caption = 'PAR: Export sales invoices to partners  ES01' where caption = 'Export sales invoices to partners  ES01'
update batch set caption = 'PAR: Export sales invoices to partners AT01' where caption = 'Export sales invoices to partners AT01'
update batch set caption = 'PAR: Export sales invoices to partners AX DE01' where caption = 'Export sales invoices to partners AX DE01'
update batch set caption = 'PAR: Export sales invoices to partners AX DE03' where caption = 'Export sales invoices to partners AX DE03'
update batch set caption = 'PAR: Export sales invoices to partners AX DK01' where caption = 'Export sales invoices to partners AX DK01'
update batch set caption = 'PAR: Export sales invoices to partners AX IS01' where caption = 'Export sales invoices to partners AX IS01'
update batch set caption = 'PAR: Export sales invoices to partners AX NO01' where caption = 'Export sales invoices to partners AX NO01'
update batch set caption = 'PAR: Export sales invoices to partners AX SE01' where caption = 'Export sales invoices to partners AX SE01'
update batch set caption = 'PAR: Export sales invoices to partners AX SE02' where caption = 'Export sales invoices to partners AX SE02'
update batch set caption = 'PAR: Export sales invoices to partners AX SK01' where caption = 'Export sales invoices to partners AX SK01'
update batch set caption = 'PAR: Export sales invoices to partners AX US01' where caption = 'Export sales invoices to partners AX US01'
update batch set caption = 'PAR: Export sales invoices to partners BE01' where caption = 'Export sales invoices to partners BE01'
update batch set caption = 'PAR: Export sales invoices to partners BE02' where caption = 'Export sales invoices to partners BE02'
update batch set caption = 'PAR: Export sales invoices to partners CH01' where caption = 'Export sales invoices to partners CH01'
update batch set caption = 'PAR: Export sales invoices to partners CY01' where caption = 'Export sales invoices to partners CY01'
update batch set caption = 'PAR: Export sales invoices to partners CZ01' where caption = 'Export sales invoices to partners CZ01'
update batch set caption = 'PAR: Export sales invoices to partners DE01' where caption = 'Export sales invoices to partners DE01'
update batch set caption = 'PAR: Export sales invoices to partners DE02' where caption = 'Export sales invoices to partners DE02'
update batch set caption = 'PAR: Export sales invoices to partners DE04' where caption = 'Export sales invoices to partners DE04'
update batch set caption = 'PAR: Export sales invoices to partners DE05' where caption = 'Export sales invoices to partners DE05'
update batch set caption = 'PAR: Export sales invoices to partners EE01 Estland' where caption = 'Export sales invoices to partners EE01 Estland'
update batch set caption = 'PAR: Export sales invoices to partners ES02' where caption = 'Export sales invoices to partners ES02'
update batch set caption = 'PAR: Export sales invoices to partners ES03' where caption = 'Export sales invoices to partners ES03'
update batch set caption = 'PAR: Export sales invoices to partners ES04' where caption = 'Export sales invoices to partners ES04'
update batch set caption = 'PAR: Export sales invoices to partners ES05' where caption = 'Export sales invoices to partners ES05'
update batch set caption = 'PAR: Export sales invoices to partners ES06' where caption = 'Export sales invoices to partners ES06'
update batch set caption = 'PAR: Export sales invoices to partners FO01' where caption = 'Export sales invoices to partners FO01'
update batch set caption = 'PAR: Export sales invoices to partners FR01' where caption = 'Export sales invoices to partners FR01'
update batch set caption = 'PAR: Export sales invoices to partners FR02' where caption = 'Export sales invoices to partners FR02'
update batch set caption = 'PAR: Export sales invoices to partners FR04' where caption = 'Export sales invoices to partners FR04'
update batch set caption = 'PAR: Export sales invoices to partners GB01002' where caption = 'Export sales invoices to partners GB01002'
update batch set caption = 'PAR: Export sales invoices to partners GB01003' where caption = 'Export sales invoices to partners GB01003'
update batch set caption = 'PAR: Export sales invoices to partners GB01004' where caption = 'Export sales invoices to partners GB01004'
update batch set caption = 'PAR: Export sales invoices to partners GB01005' where caption = 'Export sales invoices to partners GB01005'
update batch set caption = 'PAR: Export sales invoices to partners GB01006' where caption = 'Export sales invoices to partners GB01006'
update batch set caption = 'PAR: Export sales invoices to partners GB01007' where caption = 'Export sales invoices to partners GB01007'
update batch set caption = 'PAR: Export sales invoices to partners GB01008' where caption = 'Export sales invoices to partners GB01008'
update batch set caption = 'PAR: Export sales invoices to partners GB01009' where caption = 'Export sales invoices to partners GB01009'
update batch set caption = 'PAR: Export sales invoices to partners GB01011' where caption = 'Export sales invoices to partners GB01011'
update batch set caption = 'PAR: Export sales invoices to partners GB01013' where caption = 'Export sales invoices to partners GB01013'
update batch set caption = 'PAR: Export sales invoices to partners GB01014' where caption = 'Export sales invoices to partners GB01014'
update batch set caption = 'PAR: Export sales invoices to partners GB01015' where caption = 'Export sales invoices to partners GB01015'
update batch set caption = 'PAR: Export sales invoices to partners GB01016' where caption = 'Export sales invoices to partners GB01016'
update batch set caption = 'PAR: Export sales invoices to partners GB01017' where caption = 'Export sales invoices to partners GB01017'
update batch set caption = 'PAR: Export sales invoices to partners GB01018' where caption = 'Export sales invoices to partners GB01018'
update batch set caption = 'PAR: Export sales invoices to partners GB01019' where caption = 'Export sales invoices to partners GB01019'
update batch set caption = 'PAR: Export sales invoices to partners GB01020' where caption = 'Export sales invoices to partners GB01020'
update batch set caption = 'PAR: Export sales invoices to partners GB01021' where caption = 'Export sales invoices to partners GB01021'
update batch set caption = 'PAR: Export sales invoices to partners GB01022' where caption = 'Export sales invoices to partners GB01022'
update batch set caption = 'PAR: Export sales invoices to partners GB01023' where caption = 'Export sales invoices to partners GB01023'
update batch set caption = 'PAR: Export sales invoices to partners GB01024' where caption = 'Export sales invoices to partners GB01024'
update batch set caption = 'PAR: Export sales invoices to partners GB01025' where caption = 'Export sales invoices to partners GB01025'
update batch set caption = 'PAR: Export sales invoices to partners GB01026' where caption = 'Export sales invoices to partners GB01026'
update batch set caption = 'PAR: Export sales invoices to partners GB01027' where caption = 'Export sales invoices to partners GB01027'
update batch set caption = 'PAR: Export sales invoices to partners GB01028' where caption = 'Export sales invoices to partners GB01028'
update batch set caption = 'PAR: Export sales invoices to partners GB01029' where caption = 'Export sales invoices to partners GB01029'
update batch set caption = 'PAR: Export sales invoices to partners GB01030' where caption = 'Export sales invoices to partners GB01030'
update batch set caption = 'PAR: Export sales invoices to partners GB01031' where caption = 'Export sales invoices to partners GB01031'
update batch set caption = 'PAR: Export sales invoices to partners GB01032' where caption = 'Export sales invoices to partners GB01032'
update batch set caption = 'PAR: Export sales invoices to partners GB01033' where caption = 'Export sales invoices to partners GB01033'
update batch set caption = 'PAR: Export sales invoices to partners GB01034' where caption = 'Export sales invoices to partners GB01034'
update batch set caption = 'PAR: Export sales invoices to partners GB01035' where caption = 'Export sales invoices to partners GB01035'
update batch set caption = 'PAR: Export sales invoices to partners GB01036' where caption = 'Export sales invoices to partners GB01036'
update batch set caption = 'PAR: Export sales invoices to partners GB01037' where caption = 'Export sales invoices to partners GB01037'
update batch set caption = 'PAR: Export sales invoices to partners GB01038' where caption = 'Export sales invoices to partners GB01038'
update batch set caption = 'PAR: Export sales invoices to partners GB01039' where caption = 'Export sales invoices to partners GB01039'
update batch set caption = 'PAR: Export sales invoices to partners GB01040' where caption = 'Export sales invoices to partners GB01040'
update batch set caption = 'PAR: Export sales invoices to partners GB01041' where caption = 'Export sales invoices to partners GB01041'
update batch set caption = 'PAR: Export sales invoices to partners GB01042' where caption = 'Export sales invoices to partners GB01042'
update batch set caption = 'PAR: Export sales invoices to partners GB01043' where caption = 'Export sales invoices to partners GB01043'
update batch set caption = 'PAR: Export sales invoices to partners GB01044' where caption = 'Export sales invoices to partners GB01044'
update batch set caption = 'PAR: Export sales invoices to partners GB01045' where caption = 'Export sales invoices to partners GB01045'
update batch set caption = 'PAR: Export sales invoices to partners GB01046' where caption = 'Export sales invoices to partners GB01046'
update batch set caption = 'PAR: Export sales invoices to partners GB01047' where caption = 'Export sales invoices to partners GB01047'
update batch set caption = 'PAR: Export sales invoices to partners GB01048' where caption = 'Export sales invoices to partners GB01048'
update batch set caption = 'PAR: Export sales invoices to partners GB01049' where caption = 'Export sales invoices to partners GB01049'
update batch set caption = 'PAR: Export sales invoices to partners GB01052' where caption = 'Export sales invoices to partners GB01052'
update batch set caption = 'PAR: Export sales invoices to partners GB02' where caption = 'Export sales invoices to partners GB02'
update batch set caption = 'PAR: Export sales invoices to partners GB03' where caption = 'Export sales invoices to partners GB03'
update batch set caption = 'PAR: Export sales invoices to partners GB04' where caption = 'Export sales invoices to partners GB04'
update batch set caption = 'PAR: Export sales invoices to partners GB05 SC' where caption = 'Export sales invoices to partners GB05 SC'
update batch set caption = 'PAR: Export sales invoices to partners GB06 NI' where caption = 'Export sales invoices to partners GB06 NI'
update batch set caption = 'PAR: Export sales invoices to partners GR01' where caption = 'Export sales invoices to partners GR01'
update batch set caption = 'PAR: Export sales invoices to partners HU01001' where caption = 'Export sales invoices to partners HU01001'
update batch set caption = 'PAR: Export sales invoices to partners HU01002' where caption = 'Export sales invoices to partners HU01002'
update batch set caption = 'PAR: Export sales invoices to partners HU01003' where caption = 'Export sales invoices to partners HU01003'
update batch set caption = 'PAR: Export sales invoices to partners HU01004' where caption = 'Export sales invoices to partners HU01004'
update batch set caption = 'PAR: Export sales invoices to partners HU01006' where caption = 'Export sales invoices to partners HU01006'
update batch set caption = 'PAR: Export sales invoices to partners IE01' where caption = 'Export sales invoices to partners IE01'
update batch set caption = 'PAR: Export sales invoices to partners IT01' where caption = 'Export sales invoices to partners IT01'
update batch set caption = 'PAR: Export sales invoices to partners IT02' where caption = 'Export sales invoices to partners IT02'
update batch set caption = 'PAR: Export sales invoices to partners IT03' where caption = 'Export sales invoices to partners IT03'
update batch set caption = 'PAR: Export sales invoices to partners JP01' where caption = 'Export sales invoices to partners JP01'
update batch set caption = 'PAR: Export sales invoices to partners KR01' where caption = 'Export sales invoices to partners KR01'
update batch set caption = 'PAR: Export sales invoices to partners LT01 Litauen' where caption = 'Export sales invoices to partners LT01 Litauen'
update batch set caption = 'PAR: Export sales invoices to partners LV01 Letland' where caption = 'Export sales invoices to partners LV01 Letland'
update batch set caption = 'PAR: Export sales invoices to partners MT01' where caption = 'Export sales invoices to partners MT01'
update batch set caption = 'PAR: Export sales invoices to partners NL01' where caption = 'Export sales invoices to partners NL01'
update batch set caption = 'PAR: Export sales invoices to partners PL01' where caption = 'Export sales invoices to partners PL01'
update batch set caption = 'PAR: Export sales invoices to partners PL02' where caption = 'Export sales invoices to partners PL02'
update batch set caption = 'PAR: Export sales invoices to partners PT01' where caption = 'Export sales invoices to partners PT01'
update batch set caption = 'PAR: Export sales to partners' where caption = 'Export sales to partners'
update batch set caption = 'PAR: Export sales to partners GB02' where caption = 'Export sales to partners GB02'
update batch set caption = 'PAR: Export sales to partners GB03' where caption = 'Export sales to partners GB03'
update batch set caption = 'PAR: Export sales to partners GB05 SC' where caption = 'Export sales to partners GB05 SC'
update batch set caption = 'PAR: Export sales to partners NI' where caption = 'Export sales to partners NI'
update batch set caption = 'FIN: FI01 - Calculate statement' where caption = 'FI01 - Calculate statement'
update batch set caption = 'FIN: FI01 - Customer aging snapshot' where caption = 'FI01 - Customer aging snapshot'
update batch set caption = 'RET: FI01 - Post inventory' where caption = 'FI01 - Post inventory'
update batch set caption = 'FIN: FI01 - Post statement' where caption = 'FI01 - Post statement'
update batch set caption = 'FIN: FI01 - Recalculate inventory' where caption = 'FI01 - Recalculate inventory'
update batch set caption = 'RET: FI01 - Update employee discounts info subcodes' where caption = 'FI01 - Update employee discounts info subcodes'
update batch set caption = 'RET: FI01- Retail assortments job' where caption = 'FI01- Retail assortments job'
update batch set caption = 'FIN: Calculate estimated landed cost' where caption = 'FIN Calculate estimated landed cost'
update batch set caption = 'FIN: Order invoice - Internal /donations' where caption = 'FIN: Internal /donations orders invoice'
update batch set caption = 'FIN: Order invoice - APAC' where caption = 'FIN: Order invoice - APAC'
update batch set caption = 'FIN: Order invoice - daily' where caption = 'FIN: Order invoice - daily'
update batch set caption = 'FIN: Order invoice - hourly' where caption = 'FIN: Order invoice - hourly'
update batch set caption = 'RET: Fix exchange rates for gift card payments' where caption = 'Fix exchange rates for gift card payments'
update batch set caption = 'RET: FO01 - Retail assortments job' where caption = 'FO01 - Retail assortments job'
update batch set caption = 'RET: FR01 - Retail assortments job' where caption = 'FR01 - Retail assortments job'
update batch set caption = 'RET: FR02 - Retail assortments job' where caption = 'FR02 - Retail assortments job'
update batch set caption = 'RET: FR03 - Retail assortments job' where caption = 'FR03 - Retail assortments job'
update batch set caption = 'RET: FR04 - Retail assortments job' where caption = 'FR04 - Retail assortments job'
update batch set caption = 'RET: GB01 - Retail assortments job' where caption = 'GB01 - Retail assortments job'
update batch set caption = 'RET: GB02 - Retail assortments job' where caption = 'GB02 - Retail assortments job'
update batch set caption = 'RET: GB03 - Retail assortments job' where caption = 'GB03 - Retail assortments job'
update batch set caption = 'RET: GB04 - Retail assortments job' where caption = 'GB04 - Retail assortments job'
update batch set caption = 'RET: GB05 - Retail assortments job' where caption = 'GB05 - Retail assortments job'
update batch set caption = 'RET: GB06 - Retail assortments job' where caption = 'GB06 - Retail assortments job'
update batch set caption = 'RET: GR01 - Retail assortments job' where caption = 'GR01 - Retail assortments job'
update batch set caption = 'RET: HU01 - Retail assortments job' where caption = 'HU01 - Retail assortments job'
update batch set caption = 'RET: IE01 - Retail assortments job' where caption = 'IE01 - Retail assortments job'
update batch set caption = 'FIN: IS01 - Calculate statement' where caption = 'IS01 - Calculate statement'
update batch set caption = 'FIN: IS01 - Customer aging snapshot' where caption = 'IS01 - Customer aging snapshot'
update batch set caption = 'FIN: IS01 - Export vendor data to Readsoft Online' where caption = 'IS01 - Export vendor data to Readsoft Online'
update batch set caption = 'FIN: IS01 - Import invoices from XML' where caption = 'IS01 - Import invoices from XML'
update batch set caption = 'RET: IS01 - Post inventory' where caption = 'IS01 - Post inventory'
update batch set caption = 'FIN: IS01 - Post statement' where caption = 'IS01 - Post statement'
update batch set caption = 'FIN: IS01 - Recalculate inventory' where caption = 'IS01 - Recalculate inventory'
update batch set caption = 'RET: IS01 - Retail assortments job' where caption = 'IS01 - Retail assortments job'
update batch set caption = 'RET: IT01 - Retail assortments job' where caption = 'IT01 - Retail assortments job'
update batch set caption = 'RET: IT02 - Retail assortments job' where caption = 'IT02 - Retail assortments job'
update batch set caption = 'RET: IT03 - Retail assortments job' where caption = 'IT03 - Retail assortments job'
update batch set caption = 'RET: JP01 - Retail assortments job' where caption = 'JP01 - Retail assortments job'
update batch set caption = 'RET: KR01 - Retail assortments job' where caption = 'KR01 - Retail assortments job'
update batch set caption = 'SYS: Lasernet tasks' where caption = 'Lasernet tasks'
update batch set caption = 'LOG: Blue Water' where caption = 'LOG: Blue Water'
update batch set caption = 'LOG: Generate SO pick-list for WMS released' where caption = 'LOG: Generate SO pick-list for WMS released'
update batch set caption = 'LOG: Hecksher, receive booking' where caption = 'LOG: Hecksher, receive booking'
update batch set caption = 'LOG: Inbound (Type-3, Type-32) - FILE' where caption = 'LOG: Inbound (Type-3, Type-32) - FILE'
update batch set caption = 'LOG: Inbound (Type-3, Type-32) - MSMQ' where caption = 'LOG: Inbound (Type-3, Type-32) - MSMQ'
update batch set caption = 'LOG: Order packing slip (15/min)' where caption = 'LOG: Order packing slip (15/min)'
update batch set caption = 'LOG: Order packing slip (Hourly)' where caption = 'LOG: Order packing slip (Hourly)'
update batch set caption = 'LOG: Outbound (Type-4, Type-42) - FILE' where caption = 'LOG: Outbound (Type-4, Type-42) - FILE'
update batch set caption = 'LOG: Outbound (Type-4, Type-42) - MSMQ' where caption = 'LOG: Outbound (Type-4, Type-42) - MSMQ'
update batch set caption = 'LOG: Receive WMS messages - FILE' where caption = 'LOG: Receive WMS messages - FILE'
update batch set caption = 'LOG: Receive WMS messages - MSMQ' where caption = 'LOG: Receive WMS messages - MSMQ'
update batch set caption = 'LOG: Type-1 – Product master data (daily)' where caption = 'LOG: Type-1 – Product master data (daily)'
update batch set caption = 'LOG: Type-1 – Product master data (week)' where caption = 'LOG: Type-1 – Product master data (week)'
update batch set caption = 'LOG: Update integration log search table' where caption = 'LOG: Update integration log search table'
update batch set caption = 'LOG: Weeks on hand' where caption = 'LOG: Weeks on hand'
update batch set caption = 'LOG: WMS log retry processing' where caption = 'LOG: WMS log retry processing'
update batch set caption = 'RET: LT01 - Retail assortments job' where caption = 'LT01 - Retail assortments job'
update batch set caption = 'RET: LV01 - Retail assortments job' where caption = 'LV01 - Retail assortments job'
update batch set caption = 'RET: MT01 - Retail assortments job' where caption = 'MT01 - Retail assortments job'
update batch set caption = 'RET: Nl01 - Retail assortments job' where caption = 'Nl01 - Retail assortments job'
update batch set caption = 'FIN: NO01 - Calculate statement' where caption = 'NO01 - Calculate statement'
update batch set caption = 'FIN: NO01 - Customer aging snapshot' where caption = 'NO01 - Customer aging snapshot'
update batch set caption = 'RET: NO01 - Post inventory' where caption = 'NO01 - Post inventory'
update batch set caption = 'FIN: NO01 - Post statement' where caption = 'NO01 - Post statement'
update batch set caption = 'FIN: NO01 - Recalculate inventory' where caption = 'NO01 - Recalculate inventory'
update batch set caption = 'RET: NO01 - Retail assortments job' where caption = 'NO01 - Retail assortments job'
update batch set caption = 'RET: PL01 - Retail assortments job' where caption = 'PL01 - Retail assortments job'
update batch set caption = 'RET: PL02 - Retail assortments job' where caption = 'PL02 - Retail assortments job'
update batch set caption = 'RET: Process scanned lines' where caption = 'Process scanned lines'
update batch set caption = 'RET: PT01 - Retail assortments job' where caption = 'PT01 - Retail assortments job'
update batch set caption = 'FIN: ZEAS - Reminder IWF Invoices' where caption = 'Reminder IWF Invoices'
update batch set caption = 'FIN: ZEAS - Reminder/escalation' where caption = 'Reminder/escalation'
update batch set caption = 'RET: ES01 - Retail assortments job' where caption = 'Retail assortments job'
update batch set caption = 'SYS: Retail discovery batch job' where caption = 'Retail discovery batch job'
update batch set caption = 'RET: RetailAll Customer' where caption = 'RetailAll Customer'
update batch set caption = 'RET: RetailAll Daily UTC+0' where caption = 'RetailAll Daily UTC+0'
update batch set caption = 'RET: RetailAll Daily UTC+1' where caption = 'RetailAll Daily UTC+1'
update batch set caption = 'RET: RetailAll Daily UTC-6' where caption = 'RetailAll Daily UTC-6'
update batch set caption = 'RET: RetailAll Purchase Order Import' where caption = 'RetailAll Purchase Order Import'
update batch set caption = 'RET: RetailAll Staff' where caption = 'RetailAll Staff'
update batch set caption = 'RET: RetailAll Transactions' where caption = 'RetailAll Transactions'
update batch set caption = 'FIN: SE01 - Calculate statement' where caption = 'SE01 - Calculate statement'
update batch set caption = 'FIN: SE01 - Customer aging snapshot' where caption = 'SE01 - Customer aging snapshot'
update batch set caption = 'FIN: SE01 - Import invoices from XML' where caption = 'SE01 - Import invoices from XML'
update batch set caption = 'RET: SE01 - Post inventory' where caption = 'SE01 - Post inventory'
update batch set caption = 'FIN: SE01 - Post statement' where caption = 'SE01 - Post statement'
update batch set caption = 'FIN: SE01 - Recalculate inventory' where caption = 'SE01 - Recalculate inventory'
update batch set caption = 'RET: SE01 - Retail assortments job' where caption = 'SE01 - Retail assortments job'
update batch set caption = 'RET: SE01 - Update employee discounts info subcodes' where caption = 'SE01 - Update employee discounts info subcodes'
update batch set caption = 'RET: Update retail status messages' where caption = 'SE01 - Update retail status messages'
update batch set caption = 'FIN: SE02 - Calculate statement' where caption = 'SE02 - Calculate statement'
update batch set caption = 'FIN: SE02 - Customer aging snapshot' where caption = 'SE02 - Customer aging snapshot'
update batch set caption = 'FIN: SE02 - Export vendor data to Readsoft Online' where caption = 'SE02 - Export vendor data to Readsoft Online'
update batch set caption = 'FIN: SE02 - Import invoices from XML' where caption = 'SE02 - Import invoices from XML'
update batch set caption = 'RET: SE02 - Post inventory' where caption = 'SE02 - Post inventory'
update batch set caption = 'FIN: SE02 - Post statement' where caption = 'SE02 - Post statement'
update batch set caption = 'FIN: SE02 - Recalculate inventory' where caption = 'SE02 - Recalculate inventory'
update batch set caption = 'RET: SE02 - Retail assortments job' where caption = 'SE02 - Retail assortments job'
update batch set caption = 'RET: SE02 - Update employee discounts info subcodes' where caption = 'SE02 - Update employee discounts info subcodes'
update batch set caption = 'FIN: SK01 - Calculate statement' where caption = 'SK01 - Calculate statement'
update batch set caption = 'FIN: SK01 - Customer aging snapshot' where caption = 'SK01 - Customer aging snapshot'
update batch set caption = 'RET: SK01 - Post inventory' where caption = 'SK01 - Post inventory'
update batch set caption = 'FIN: SK01 - Post statement' where caption = 'SK01 - Post statement'
update batch set caption = 'FIN: SK01 - Recalculate inventory' where caption = 'SK01 - Recalculate inventory'
update batch set caption = 'RET: SK01 - Retail assortments job' where caption = 'SK01 - Retail assortments job'
update batch set caption = 'SOP: Create sales order (committed campaigns, 5 min job)' where caption = 'SOP: Create sales order (committed campaigns, 5 min job)'
update batch set caption = 'SOP: Create sales order (not campaign, 2 min job)' where caption = 'SOP: Create sales order (not campaign, 2 min job)'
update batch set caption = 'SOP: Create sales order (not campaign, 5 min job)' where caption = 'SOP: Create sales order (not campaign, 5 min job)'
update batch set caption = 'SOP: Generate Access User Groups' where caption = 'SOP: Generate Access User Groups'
update batch set caption = 'SYS Change based alerts' where caption = 'SYS Change based alerts'
update batch set caption = 'RET: IS01 - Update employee discounts info subcodes' where caption = 'Update employee discounts info subcodes'
update batch set caption = 'RET: NO01 - Update employee discounts info subcodes' where caption = 'Update employee discounts info subcodes'
update batch set caption = 'FIN: US01 - Calculate statement' where caption = 'US01 - Calculate statement'
update batch set caption = 'FIN: US01 - Customer aging snapshot' where caption = 'US01 - Customer aging snapshot'
update batch set caption = 'FIN: US01 - Export vendor data to Readsoft Online' where caption = 'US01 - Export vendor data to Readsoft Online'
update batch set caption = 'FIN: US01 - Import invoices from XML' where caption = 'US01 - Import invoices from XML'
update batch set caption = 'RET: US01 - Post inventory' where caption = 'US01 - Post inventory'
update batch set caption = 'FIN: US01 - Post statement' where caption = 'US01 - Post statement'
update batch set caption = 'FIN: US01 - Recalculate inventory' where caption = 'US01 - Recalculate inventory'
update batch set caption = 'RET: US01 - Retail assortments job' where caption = 'US01 - Retail assortments job'
update batch set caption = 'RET: US01 - Update employee discounts info subcodes' where caption = 'US01 Update employee discounts info subcodes'
update batch set caption = 'SYS: Workflow due date processing' where caption = 'Workflow due date processing'
update batch set caption = 'SYS: Workflow line-item notifications' where caption = 'Workflow line-item notifications'
update batch set caption = 'SYS: Workflow message processing' where caption = 'Workflow message processing'
update batch set caption = 'FIN: ZEAS - Export vendor data to Readsoft Online' where caption = 'ZEAS - Export vendor data to Readsoft Online'
update batch set caption = 'FIN: ZEAS - Import currency exchange rates from Danish National Bank' where caption = 'ZEAS - Import currency exchange rates from Danish National Bank'
update batch set caption = 'FIN: ZEAS - Import invoices from XML' where caption = 'ZEAS - Import invoices from XML'
update batch set caption = 'FIN: ZEAS - Reminder/escalation' where caption = 'ZEAS - Reminder/escalation'
update batch set caption = 'FIN: ZEAS - Send batch mails originating from MW-Workflow' where caption = 'ZEAS - Send batch mails originating from MW-Workflow'
update batch set caption = 'FIN: ZEAS - Update charge group on vendors and items' where caption = 'ZEAS - Update charge group on vendors and items'
