/****** Object:  Index [I_2096RECID]    Script Date: 06-10-2017 13:04:10 ******/
ALTER TABLE [dbo].[BATCHJOB] ADD  CONSTRAINT [I_2096RECID] PRIMARY KEY CLUSTERED 
(
	[RECID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75)
GO

/****** Object:  Index [I_2096COMPANYIDX]    Script Date: 06-10-2017 13:04:02 ******/
CREATE NONCLUSTERED INDEX [I_2096COMPANYIDX] ON [dbo].[BATCHJOB]
(
	[COMPANY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75)
GO


CREATE NONCLUSTERED INDEX [I_2096RUNTIMEJOBS] ON [dbo].[BATCHJOB]
(
	[FINISHING] ASC,
	[RUNTIMEJOB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75)
GO

/****** Object:  Index [I_2096STATUSRECID]    Script Date: 06-10-2017 13:04:54 ******/
CREATE NONCLUSTERED INDEX [I_2096STATUSRECID] ON [dbo].[BATCHJOB]
(
	[FINISHING] ASC,
	[STATUS] ASC,
	[STARTDATETIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75)
GO

/****** Object:  Index [I_2272BATCH]    Script Date: 06-10-2017 13:05:21 ******/
CREATE NONCLUSTERED INDEX [I_2272BATCH] ON [dbo].[BATCHHISTORY]
(
	[BATCHID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75)
GO
/****** Object:  Index [I_2272BATCHJOB]    Script Date: 06-10-2017 13:05:47 ******/
CREATE NONCLUSTERED INDEX [I_2272BATCHJOB] ON [dbo].[BATCHHISTORY]
(
	[BATCHJOBID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75)
GO

/****** Object:  Index [I_2272BATCHJOBHISTORY]    Script Date: 06-10-2017 13:05:58 ******/
CREATE NONCLUSTERED INDEX [I_2272BATCHJOBHISTORY] ON [dbo].[BATCHHISTORY]
(
	[BATCHJOBHISTORYID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75)
GO

/****** Object:  Index [I_2272EGBCSTARTDATETIME]    Script Date: 06-10-2017 13:10:25 ******/
CREATE NONCLUSTERED INDEX [I_2272EGBCSTARTDATETIME] ON [dbo].[BATCHHISTORY]
(
	[STARTDATETIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)
GO
/****** Object:  Index [I_2272RECID]    Script Date: 06-10-2017 13:10:39 ******/
ALTER TABLE [dbo].[BATCHHISTORY] ADD  CONSTRAINT [I_2272RECID] PRIMARY KEY CLUSTERED 
(
	[RECID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75)
GO

/****** Object:  Index [I_2272ZEBSTATUSIDX]    Script Date: 06-10-2017 13:10:53 ******/
CREATE NONCLUSTERED INDEX [I_2272ZEBSTATUSIDX] ON [dbo].[BATCHHISTORY]
(
	[STATUS] ASC,
	[BATCHJOBHISTORYID] ASC,
	[RUNTIMETASK] ASC
)
INCLUDE ( 	[CAPTION],
	[RECID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90)
GO
/****** Object:  Index [I_2100BATCHID]    Script Date: 06-10-2017 13:11:20 ******/
CREATE CLUSTERED INDEX [I_2100BATCHID] ON [dbo].[BATCHCONSTRAINTS]
(
	[BATCHID] ASC,
	[DEPENDSONBATCHID] ASC,
	[EXPECTEDSTATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75)
GO

/****** Object:  Index [I_2100RECID]    Script Date: 06-10-2017 13:11:34 ******/
ALTER TABLE [dbo].[BATCHCONSTRAINTS] ADD  CONSTRAINT [I_2100RECID] PRIMARY KEY NONCLUSTERED 
(
	[RECID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75)
GO

/****** Object:  Index [I_2100SERVERSEARCH]    Script Date: 06-10-2017 13:11:44 ******/
CREATE NONCLUSTERED INDEX [I_2100SERVERSEARCH] ON [dbo].[BATCHCONSTRAINTS]
(
	[BATCHID] ASC,
	[EXPECTEDSTATUS] ASC,
	[DEPENDSONBATCHID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75)
GO






