use AXKNI_MOVE
drop table dbo.TMP_LedgerTrans
GO
Exec dbo.LogProgressInfo 'Step 1 - SQL COUNT af LedgerTrans startet','Step0',1
select * 
FROM OPENQUERY(S2AX40KNI, 'SELECT COUNT(*)  
					  FROM dbo.LEDGERTRANS WHERE SUBSTR(NLS_LOWER(DATAAREAID),1,7) = ''kni''')
GO
Exec dbo.LogProgressInfo 'Step 1 - SQL COUNT af LedgerTrans startet','Step0',2
GO
Exec dbo.LogProgressInfo 'Step 1a - SQL Overførsel af LedgerTrans startet','Step1',1
select * into AXKNI_MOVE.dbo.TMP_LedgerTrans
FROM OPENQUERY(S2AX40KNI, 'SELECT ACCOUNTNUM, CREATEDBY, TO_CHAR(CREATEDTIME) AS CREATEDTIME, MODIFIEDBY, TO_CHAR(MODIFIEDTIME) AS MODIFIEDTIME, MODIFIEDDATE, 
					   EMPLDIMENSION3_, EMPLDIMENSION2_, EMPLDIMENSION,   
                      TO_CHAR(TAXREFID) AS TAXREFID, LEDGERPOSTINGJOURNALID, TO_CHAR(FURTHERPOSTINGTYPE) AS FURTHERPOSTINGTYPE, TO_CHAR(EUROTRIANGULATION) AS EUROTRIANGULATION, 
                      TO_CHAR(AMOUNTMSTSECOND) AS AMOUNTMSTSECOND, JOURNALIZENUM, PAYMMODE, COMPANYBANKACCOUNTID, THIRDPARTYBANKACCOUNTID, 
					  OPERATIONSTAX, TO_CHAR(PERIODCODE) AS PERIODCODE, 
                      PAYMREFERENCE, DOCUMENTNUM, TO_CHAR(CREDITING) AS CREDITING, TO_CHAR(CORRECT) AS CORRECT, TO_CHAR(POSTING) AS POSTING, TO_CHAR(ALLOCATELEVEL) AS ALLOCATELEVEL, 
					TO_CHAR(JOURNALIZESEQNUM) AS JOURNALIZESEQNUM, JOURNALNUM, DOCUMENTDATE, QTY, DIMENSION3_, DIMENSION2_,
					DIMENSION, To_CHAR(TRANSTYPE) AS TRANSTYPE,CURRENCYCODE,TO_CHAR(AMOUNTCUR) AS AMOUNTCUR, 
                      TO_CHAR(AMOUNTMST) AS AMOUNTMST, TXT, VOUCHER, TRANSDATE, CREATEDDATE, TO_CHAR(CREATEDTRANSACTIONID) AS CREATEDTRANSACTIONID, 
					DATAAREAID, TO_CHAR(RECID) AS RECID  
					  FROM dbo.LEDGERTRANS WHERE SUBSTR(NLS_LOWER(DATAAREAID),1,7) = ''kni''') 
Exec dbo.LogProgressInfo 'Step 1a - SQL Overførsel af LedgerTrans afsluttet','Step1',2
GO
Exec dbo.LogProgressInfo 'Step 1b - Update LedgerTrans startet','Step1',1
UPDATE dbo.TMP_LedgerTrans 
set 
 EMPLDIMENSION3_ = dbo.LP_STR(EMPLDIMENSION3_)
,EMPLDIMENSION2_ = dbo.LP_STR(EMPLDIMENSION2_)
,EMPLDIMENSION = dbo.LP_STR(EMPLDIMENSION)
,JOURNALIZENUM = dbo.LP_STR(JOURNALIZENUM)
,DOCUMENTNUM = dbo.LP_STR(DOCUMENTNUM)
,LEDGERPOSTINGJOURNALID = dbo.LP_STR(LEDGERPOSTINGJOURNALID)
,PAYMMODE = dbo.LP_STR(PAYMMODE)
,COMPANYBANKACCOUNTID = dbo.LP_STR(COMPANYBANKACCOUNTID)
,THIRDPARTYBANKACCOUNTID = dbo.LP_STR(THIRDPARTYBANKACCOUNTID)
,PAYMREFERENCE = dbo.LP_STR(PAYMREFERENCE)

,DIMENSION3_ = dbo.LP_STR(DIMENSION3_)
,DIMENSION2_ = dbo.LP_STR(DIMENSION2_)
,DIMENSION = dbo.LP_STR(DIMENSION)
,CREATEDBY = dbo.LP_STR(CREATEDBY)
Exec dbo.LogProgressInfo 'Step 1b - Update LedgerTrans afsluttet','Step1',2

-- ################
Exec dbo.LogProgressInfo 'Step 2 - SQL Overførsel af LedgerBalTrans','Step2',1
drop table dbo.TMP_LedgerBalTrans
GO
select * into AXKNI_MOVE.dbo.TMP_LedgerBalTrans
FROM OPENQUERY(S2AX40KNI, 'SELECT ACCOUNTNUM
        ,TRANSDATE
        ,TO_CHAR(DEBITMST) AS DEBITMST
        ,TO_CHAR(CREDITMST) AS CREDITMST
        ,TO_CHAR(DEBITOPRMST) AS DEBITOPRMST
        ,TO_CHAR(CREDITOPRMST) AS CREDITOPRMST
        ,TO_CHAR(DEBITTAXMST) AS DEBITTAXMST
        ,TO_CHAR(CREDITTAXMST) AS CREDITTAXMST
        ,TO_CHAR(PERIODCODE) AS PERIODCODE
        ,TO_CHAR(DEBITMSTSECOND) AS DEBITMSTSECOND
        ,TO_CHAR(CREDITMSTSECOND) AS CREDITMSTSECOND
        ,TO_CHAR(DEBITOPRMSTSECOND) AS DEBITOPRMSTSECOND
        ,TO_CHAR(CREDITOPRMSTSECOND) AS CREDITOPRMSTSECOND
        ,TO_CHAR(DEBITTAXMSTSECOND) AS DEBITTAXMSTSECOND
        ,TO_CHAR(CREDITTAXMSTSECOND) AS CREDITTAXMSTSECOND
        ,TO_CHAR(QTY) AS QTY
        ,TO_CHAR(SYSTEMGENERATEDULTIMO ) AS SYSTEMGENERATEDULTIMO
        ,TO_CHAR(LEDGERBALANCESVARIANT) AS LEDGERBALANCESVARIANT
        ,DATAAREAID
        ,TO_CHAR(RECID) AS RECID
 FROM dbo.LEDGERBALANCESTRANS WHERE SUBSTR(NLS_LOWER(DATAAREAID),1,7) = ''kni''')
Exec dbo.LogProgressInfo 'Step 2 - SQL Overførsel af LedgerBalTrans afsluttet','Step2',2
-- ################
Exec dbo.LogProgressInfo 'Step 3 - SQL Overførsel af LedgerBalDimTrans ','Step3',1
drop table dbo.TMP_LedgerBalDimTrans
GO
select * into AXKNI_MOVE.dbo.TMP_LedgerBalDimTrans
FROM OPENQUERY(S2AX40KNI, 'SELECT TO_CHAR(DEBITMST)             AS DEBITMST
      ,TO_CHAR(DEBITOPRMST)          AS DEBITOPRMST          
      ,TO_CHAR(DEBITTAXMST)           AS DEBITTAXMST
      ,DIMENSION            
      ,DIMENSION2_
      ,DIMENSION3_
      ,ACCOUNTNUM
      ,TO_CHAR(CREDITMST)             AS CREDITMST
      ,TO_CHAR(CREDITOPRMST)          AS CREDITOPRMST
      ,TO_CHAR(CREDITTAXMST)          AS CREDITTAXMST
      ,TO_CHAR(PERIODCODE)            AS PERIODCODE
      ,TRANSDATE
      ,TO_CHAR(CREDITMSTSECOND)       AS CREDITMSTSECOND
      ,TO_CHAR(DEBITMSTSECOND)        AS DEBITMSTSECOND
      ,TO_CHAR(DEBITOPRMSTSECOND)     AS DEBITOPRMSTSECOND
      ,TO_CHAR(CREDITOPRMSTSECOND)    AS CREDITOPRMSTSECOND
      ,TO_CHAR(DEBITTAXMSTSECOND)     AS DEBITTAXMSTSECOND
      ,TO_CHAR(CREDITTAXMSTSECOND)    AS CREDITTAXMSTSECOND
      ,TO_CHAR(QTY)                   AS QTY
      ,TO_CHAR(SYSTEMGENERATEDULTIMO) AS SYSTEMGENERATEDULTIMO
      ,TO_CHAR(LEDGERBALANCESVARIANT) AS LEDGERBALANCESVARIANT
      ,DATAAREAID            
      ,TO_CHAR(RECID)                 AS RECID
 FROM dbo.LEDGERBALANCESDIMTRANS WHERE SUBSTR(NLS_LOWER(DATAAREAID),1,7) = ''kni''')
Exec dbo.LogProgressInfo 'Step 3 - SQL Overførsel af LedgerBalDimTrans afsluttet','Step3',2
GO 
Exec dbo.LogProgressInfo 'Step 3a - Opdatering af LedgerBalDimTrans','Step3a',1
UPDATE dbo.TMP_LedgerBalDimTrans 
set 
DIMENSION3_ = dbo.LP_STR(DIMENSION3_)
,DIMENSION2_ = dbo.LP_STR(DIMENSION2_)
,DIMENSION = dbo.LP_STR(DIMENSION)
,ACCOUNTNUM = dbo.LP_STR(ACCOUNTNUM)
GO
Exec dbo.LogProgressInfo 'Step 3a - Opdatering af LedgerBalDimTrans afsluttet','Step3a',2
-- ########################
Exec dbo.LogProgressInfo 'Step 4 - SQL Overførsel af LEDGERJOURNALTABLE ','Step4',1
drop table dbo.TMP_LEDGERJOURNALTABLE
GO
select * into AXKNITEST.dbo.TMP_LEDGERJOURNALTABLE
FROM OPENQUERY(S2AX40TEST, 'SELECT 
 JOURNALNUM
 ,NAME
 ,VOUCHERSERIES
 ,LOG
 ,TO_CHAR(JOURNALTYPE) as JOURNALTYPE
 ,TO_CHAR(SYSTEMBLOCKED) as SYSTEMBLOCKED
 ,USERBLOCKID
 ,OFFSETACCOUNT
 ,POSTEDDATE
 ,REJECTEDBY
 ,REPORTEDASREADYBY
 ,APPROVEDBY
 ,JOURNALNAME
 ,TO_CHAR(POSTED) as POSTED
 ,TO_CHAR(OFFSETACCOUNTTYPE) as OFFSETACCOUNTTYPE
 ,INUSEBY
 ,GROUPBLOCKID
 ,DIMENSION
 ,DIMENSION2_
 ,DIMENSION3_
 ,ORIGINALJOURNALNUM
 ,CURRENCYCODE
 ,TO_CHAR(FIXEDEXCHRATE) as FIXEDEXCHRATE
 ,TO_CHAR(DETAILSUMMARYPOSTING) as DETAILSUMMARYPOSTING
 ,DOCUMENTNUM
 ,TO_CHAR(EXCHRATESECONDARY) as EXCHRATESECONDARY
 ,TO_CHAR(EXCHRATE) as EXCHRATE
 ,TO_CHAR(EUROTRIANGULATION) as EUROTRIANGULATION
 ,TO_CHAR(FIXEDOFFSETACCOUNT) as FIXEDOFFSETACCOUNT
 ,TO_CHAR(JOURNALTOTALCREDIT) as JOURNALTOTALCREDIT
 ,TO_CHAR(JOURNALTOTALDEBIT) as JOURNALTOTALDEBIT
 ,TO_CHAR(JOURNALTOTALOFFSETBALANCE) as JOURNALTOTALOFFSETBALANCE
 ,TO_CHAR(REMOVELINEAFTERPOSTING) as REMOVELINEAFTERPOSTING
 ,TO_CHAR(CURRENTOPERATIONSTAX) as CURRENTOPERATIONSTAX
 ,TO_CHAR(LEDGERJOURNALINCLTAX) as LEDGERJOURNALINCLTAX
 ,ORIGINALCOMPANY
 ,TO_CHAR(SESSIONID) as SESSIONID
 ,TO_CHAR(SESSIONLOGINTIME) as SESSIONLOGINTIME
 ,SESSIONLOGINDATE
 ,TO_CHAR(BANKREMITTANCETYPE) as BANKREMITTANCETYPE
 ,BANKACCOUNTID
 ,TO_CHAR(PROTESTSETTLEDBILL) as PROTESTSETTLEDBILL
 ,TO_CHAR(CUSTVENDNEGINSTPROTESTPROCESS) as CUSTVENDNEGINSTPROTESTPROCESS
 ,TO_CHAR(VOUCHERALLOCATEDATPOSTING) as VOUCHERALLOCATEDATPOSTING
 ,TO_CHAR(NUMOFLINES) as NUMOFLINES
 ,TO_CHAR(LINESLIMITBEFOREDISTRIBUTION) as LINESLIMITBEFOREDISTRIBUTION
 ,TO_CHAR(DC4IMPORT) as DC4IMPORT
 ,MODIFIEDDATE
 ,TO_CHAR(MODIFIEDTIME) as MODIFIEDTIME
 ,MODIFIEDBY
 ,CREATEDDATE
 ,TO_CHAR(CREATEDTIME) as CREATEDTIME
 ,CREATEDBY
 ,DATAAREAID
 ,TO_CHAR(RECVERSION) as RECVERSION
 ,TO_CHAR(RECID) as RECID
 FROM dbo.LEDGERJOURNALTABLE WHERE SUBSTR(NLS_LOWER(DATAAREAID),1,7) = ''kni''')
Exec dbo.LogProgressInfo 'Step 4 - SQL Overførsel af LEDGERJOURNALTABLE afsluttet','Step4',2


-- ########################
Exec dbo.LogProgressInfo 'Step 5 - SQL Overførsel af LEDGERJOURNALTRANS','Step5',1
drop table dbo.TMP_LEDGERJOURNALTRANS
GO
select * into AXKNITEST.dbo.TMP_LEDGERJOURNALTRANS
FROM OPENQUERY(S2AX40KNI, 'SELECT 
  JOURNALNUM
 ,TO_CHAR(LINENUM) as LINENUM
 ,TO_CHAR(ACCOUNTTYPE) as ACCOUNTTYPE
 ,ACCOUNTNUM
 ,COMPANY
 ,TXT
 ,TO_CHAR(AMOUNTCURDEBIT) as AMOUNTCURDEBIT
 ,CURRENCYCODE
 ,TO_CHAR(EXCHRATE) as EXCHRATE
 ,TAXGROUP
 ,TO_CHAR(QTY) as QTY
 ,DIMENSION
 ,DIMENSION2_
 ,DIMENSION3_
 ,BANKNEGINSTRECIPIENTNAME
 ,TO_CHAR(POSTDATEDCHECK_MY) as POSTDATEDCHECK_MY
 ,TO_CHAR(PRICE) as PRICE
 ,DEL_CORRECTIVEREASON
 ,DEL_CORRECTEDINVOICEID
 ,TO_CHAR(INTERCODIMENSION) as INTERCODIMENSION
 ,TO_CHAR(INTERCODIMENSION2_) as INTERCODIMENSION2_
 ,TO_CHAR(INTERCODIMENSION3_) as INTERCODIMENSION3_
 ,TO_CHAR(SETTLEVOUCHER) as SETTLEVOUCHER
 ,POSTINGPROFILE
 ,VOUCHER
 ,TO_CHAR(AMOUNTCURCREDIT) as AMOUNTCURCREDIT
 ,TO_CHAR(PAYMENTSTATUS) as PAYMENTSTATUS
 ,TO_CHAR(CASHDISCAMOUNT) as CASHDISCAMOUNT
 ,TO_CHAR(VENDTRANSID) as VENDTRANSID
 ,TO_CHAR(CUSTTRANSID) as CUSTTRANSID
 ,TO_CHAR(REMAINAMOUNT) as REMAINAMOUNT
 ,TAXCODE
 ,OFFSETACCOUNT
 ,TO_CHAR(BANKDEPOSITVOUCHER) as BANKDEPOSITVOUCHER
 ,PAYMREFERENCE
 ,BANKDEPOSITNUM
 ,PAYMSPEC
 ,PAYMMODE
 ,TO_CHAR(OFFSETACCOUNTTYPE) as OFFSETACCOUNTTYPE
 ,BANKTRANSTYPE
 ,OFFSETCOMPANY
 ,OFFSETTXT
 ,PAYMENTNOTES
 ,FOREIGNVOUCHER
 ,FOREIGNCOMPANY
 ,TO_CHAR(DEL_FOREIGNTAX) as DEL_FOREIGNTAX
 ,TO_CHAR(TRANSFERRED) as TRANSFERRED
 ,TO_CHAR(CANCEL) as CANCEL
 ,TO_CHAR(NOEDIT) as NOEDIT
 ,TO_CHAR(INVISIBLE) as INVISIBLE
 ,TRANSDATE
 ,TO_CHAR(TRANSACTIONTYPE) as TRANSACTIONTYPE
 ,DOCUMENTDATE
 ,DOCUMENTNUM
 ,TO_CHAR(APPROVED) as APPROVED
 ,APPROVEDBY
 ,PAYMID
 ,TO_CHAR(FREQVALUE) as FREQVALUE
 ,TO_CHAR(FREQCODE) as FREQCODE
 ,DUE
 ,DATECASHDISC
 ,TRANSFERREDBY
 ,LOADINGDATE
 ,FILECREATED
 ,PAYMENTACCOUNT
 ,INVOICE
 ,TRANSFERREDTO
 ,TO_CHAR(TRANSFER) as TRANSFER
 ,LASTTRANSFERRED
 ,TRANSFERREDON
 ,TO_CHAR(PURCHLEDGERPOSTING) as PURCHLEDGERPOSTING
 ,BANKCHEQUENUM
 ,PAYMENT
 ,CASHDISCCODE
 ,TO_CHAR(EXCHRATESECOND) as EXCHRATESECOND
 ,TO_CHAR(TRIANGULATION) as TRIANGULATION
 ,TAXITEMGROUP
 ,VATNUMJOURNAL
 ,TO_CHAR(LISTCODE) as LISTCODE
 ,TO_CHAR(FURTHERPOSTINGTYPE) as FURTHERPOSTINGTYPE
 ,PURCHIDRANGE
 ,TO_CHAR(POOLRECID) as POOLRECID
 ,TO_CHAR(PREPAYMENT) as PREPAYMENT
 ,IMPORTDATE
 ,DEL_OCRLINE
 ,BANKCENTRALBANKPURPOSECODE
 ,BANKCENTRALBANKPURPOSETEXT
 ,CUSTVENDBANKACCOUNTID
 ,TO_CHAR(PAYMENTSEQUENCENUM) as PAYMENTSEQUENCENUM
 ,TO_CHAR(ASSETTRANSTYPE) as ASSETTRANSTYPE
 ,TO_CHAR(DEL_ASSETTOFROMRECID) as DEL_ASSETTOFROMRECID
 ,ASSETBUDGETMODEL
 ,ASSETID
 ,TO_CHAR(ASSETBUDGETPOSTINGSTATUS) as ASSETBUDGETPOSTINGSTATUS
 ,TO_CHAR(ASSETDEPRECIATIONTIME) as ASSETDEPRECIATIONTIME
 ,ASSETREFASSETID
 ,PROJTAXGROUPSALES
 ,PROJTAXITEMGROUPSALES
 ,ERRORCODEPAYMENT
 ,TO_CHAR(FURTHERPOSTINGRECID) as FURTHERPOSTINGRECID
 ,TO_CHAR(TAXDIRECTIONCONTROL) as TAXDIRECTIONCONTROL
 ,TO_CHAR(RESERVETRANSID) as RESERVETRANSID
 ,TO_CHAR(DEL_ASSETSECTION179TRANS) as DEL_ASSETSECTION179TRANS
 ,TO_CHAR(ASSETREVALUATIONAMOUNT) as ASSETREVALUATIONAMOUNT
 ,TO_CHAR(ASSETREVALUATIONTRANS) as ASSETREVALUATIONTRANS
 ,TO_CHAR(ASSETCONSUMPTIONQTY) as ASSETCONSUMPTIONQTY
 ,ASSETBOOKID
 ,TO_CHAR(CUSTVENDNEGINSTPROTESTREASON) as CUSTVENDNEGINSTPROTESTREASON
 ,TO_CHAR(BANKREMITTANCETYPE) as BANKREMITTANCETYPE
 ,BANKREMITTANCEFILEID
 ,BANKACCOUNTID
 ,BANKPROMISSORYNOTENUM
 ,PROJEMPLID
 ,DEL_PAYMITEMCODEID
 ,BANKBILLOFEXCHANGENUM
 ,NEGINSTID
 ,TAXWITHHOLDGROUP
 ,DC_CONTRACTID
 ,TO_CHAR(DC_CONTRACTVERSION) as DC_CONTRACTVERSION
 ,DC_VENDAPPROVEID
 ,MODIFIEDDATE
 ,TO_CHAR(MODIFIEDTIME) as MODIFIEDTIME
 ,MODIFIEDBY
 ,CREATEDDATE
 ,TO_CHAR(CREATEDTIME) as CREATEDTIME
 ,CREATEDBY
 ,DATAAREAID
 ,TO_CHAR(RECVERSION) as RECVERSION
 ,TO_CHAR(RECID) as RECID
 FROM dbo.LEDGERJOURNALTRANS WHERE SUBSTR(NLS_LOWER(DATAAREAID),1,7) = ''kni''')
Exec dbo.LogProgressInfo 'Step 5 - SQL Overførsel af LEDGERJOURNALTRANS afsluttet','Step5',2