declare @Barcode varchar(40)
select @Barcode = '5000394063525'

--SELECT STOREBARCODE FROM  RCMSUPSTOREBARCODETABLE  where STOREBARCODE = @Barcode
--SELECT ITEMBARCODE FROM  RCMSUPSTOREBARCODETABLE  where ITEMBARCODE = @Barcode
--SELECT ITEMBARCODE FROM RCMINVENTITEMBARCODE WHERE     (ITEMBARCODE = @Barcode)
--SELECT STOREBARCODE FROM RCMSupAssortmentLines WHERE STOREBARCODE = @Barcode

SELECT 'RCMSUPSTOREBARCODETABLE (S)',count(*) FROM  RCMSUPSTOREBARCODETABLE  where STOREBARCODE = @Barcode
SELECT 'RCMSUPSTOREBARCODETABLE (I)',count(*) FROM  RCMSUPSTOREBARCODETABLE  where ITEMBARCODE = @Barcode
select 'DIFF (S) og (I)',count(*) from RCMSUPSTOREBARCODETABLE  where ITEMBARCODE <>STOREBARCODE and STOREBARCODE = @Barcode
SELECT 'RCMINVENTITEMBARCODE',count(*) FROM RCMINVENTITEMBARCODE WHERE     (ITEMBARCODE = @Barcode)
SELECT 'RCMSupAssortmentLines',count(*) FROM RCMSupAssortmentLines WHERE STOREBARCODE = @Barcode