-------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------
UPDATE    RCMSUPSTOREBARCODETABLE
SET              ISTRADEGOODS = RCMINVENTITEMGROUPVIRTUAL.ISTRADEGOODS
FROM         RCMSUPSTOREBARCODETABLE INNER JOIN
                      INVENTTABLE ON RCMSUPSTOREBARCODETABLE.ITEMID = INVENTTABLE.ITEMID AND 
                      RCMSUPSTOREBARCODETABLE.DATAAREAID = INVENTTABLE.DATAAREAID INNER JOIN
                      RCMINVENTITEMGROUPVIRTUAL ON RCMSUPSTOREBARCODETABLE.DATAAREAID = RCMINVENTITEMGROUPVIRTUAL.DATAAREAID AND 
                      INVENTTABLE.ITEMGROUPID = RCMINVENTITEMGROUPVIRTUAL.ITEMGROUPID
-------------------------------------------------------------------------------------------------------------------------------------
UPDATE    RCMSUPSTOREBARCODETABLE
SET              LOOKUPCODE = RCMINVENTITEMBARCODE.ITEMBARCODE
FROM         RCMSUPSTOREBARCODETABLE INNER JOIN
                      INVENTITEMBARCODE ON RCMSUPSTOREBARCODETABLE.ITEMID = INVENTITEMBARCODE.ITEMID AND 
                      RCMSUPSTOREBARCODETABLE.DATAAREAID = INVENTITEMBARCODE.DATAAREAID INNER JOIN
                      RCMINVENTITEMBARCODE ON INVENTITEMBARCODE.DATAAREAID = RCMINVENTITEMBARCODE.DATAAREAID AND 
                      INVENTITEMBARCODE.ITEMBARCODE = RCMINVENTITEMBARCODE.ITEMBARCODE
-------------------------------------------------------------------------------------------------------------------------------------
UPDATE    RCMSUPSTOREBARCODETABLE
SET              STOREORDERITEMMAINGROUP = RCMGROUPING.PARENTID
FROM         RCMSUPSTOREBARCODETABLE INNER JOIN
                      RCMGROUPING ON RCMSUPSTOREBARCODETABLE.DATAAREAID = RCMGROUPING.DATAAREAID INNER JOIN
                      RCMPARAMETERSVIRTUAL ON RCMSUPSTOREBARCODETABLE.DATAAREAID = RCMPARAMETERSVIRTUAL.DATAAREAID AND 
                      RCMGROUPING.ROOTPARENT = RCMPARAMETERSVIRTUAL.GROUPSTOREORDERITEMMAIN INNER JOIN
                      INVENTTABLE ON RCMSUPSTOREBARCODETABLE.ITEMID = INVENTTABLE.ITEMID AND RCMGROUPING.REFRECID = INVENTTABLE.RECID
WHERE     (RCMGROUPING.REFTABLEID = 175) AND RCMSUPSTOREBARCODETABLE.STOREORDERITEMMAINGROUP = ''
