use AXKNI_MOVE
UPDATE AXKNI_MOVE.dbo.TMP_LEDGERJOURNALTRANS
set
 JOURNALNUM = dbo.LP_STR(JOURNALNUM)
 ,ACCOUNTNUM = dbo.LP_STR(ACCOUNTNUM)
 ,COMPANY = dbo.LP_STR(COMPANY)
 ,TXT = dbo.LP_STR(TXT)
 ,CURRENCYCODE = dbo.LP_STR(CURRENCYCODE)
 ,TAXGROUP = dbo.LP_STR(TAXGROUP)
 ,DIMENSION = dbo.LP_STR(DIMENSION)
 ,DIMENSION2_ = dbo.LP_STR(DIMENSION2_)
 ,DIMENSION3_ = dbo.LP_STR(DIMENSION3_)
 ,BANKNEGINSTRECIPIENTNAME = dbo.LP_STR(BANKNEGINSTRECIPIENTNAME)
 ,DEL_CORRECTEDINVOICEID = dbo.LP_STR(DEL_CORRECTEDINVOICEID)
 ,INTERCODIMENSION = dbo.LP_STR(INTERCODIMENSION)
 ,INTERCODIMENSION2_ = dbo.LP_STR(INTERCODIMENSION2_)
 ,INTERCODIMENSION3_ = dbo.LP_STR(INTERCODIMENSION3_)
 ,POSTINGPROFILE = dbo.LP_STR(POSTINGPROFILE)
 ,VOUCHER = dbo.LP_STR(VOUCHER)
 ,TAXCODE = dbo.LP_STR(TAXCODE)
 ,OFFSETACCOUNT = dbo.LP_STR(OFFSETACCOUNT)
 ,PAYMREFERENCE = dbo.LP_STR(PAYMREFERENCE)
 ,BANKDEPOSITNUM = dbo.LP_STR(BANKDEPOSITNUM)
 ,PAYMSPEC = dbo.LP_STR(PAYMSPEC)
 ,PAYMMODE = dbo.LP_STR(PAYMMODE)
 ,BANKTRANSTYPE = dbo.LP_STR(BANKTRANSTYPE)
 ,OFFSETCOMPANY = dbo.LP_STR(OFFSETCOMPANY)
 ,OFFSETTXT = dbo.LP_STR(OFFSETTXT)
 ,PAYMENTNOTES = dbo.LP_STR(PAYMENTNOTES)
 ,FOREIGNVOUCHER = dbo.LP_STR(FOREIGNVOUCHER)
 ,FOREIGNCOMPANY = dbo.LP_STR(FOREIGNCOMPANY)
 ,DOCUMENTNUM = dbo.LP_STR(DOCUMENTNUM)
 ,APPROVEDBY = dbo.LP_STR(APPROVEDBY)
 ,PAYMID = dbo.LP_STR(PAYMID)
 ,TRANSFERREDBY = dbo.LP_STR(TRANSFERREDBY)
 ,PAYMENTACCOUNT = dbo.LP_STR(PAYMENTACCOUNT)
 ,INVOICE = dbo.LP_STR(INVOICE)
 ,TRANSFERREDTO = dbo.LP_STR(TRANSFERREDTO)
 ,BANKCHEQUENUM = dbo.LP_STR(BANKCHEQUENUM)
 ,PAYMENT = dbo.LP_STR(PAYMENT)
 ,CASHDISCCODE = dbo.LP_STR(CASHDISCCODE)
 ,TAXITEMGROUP = dbo.LP_STR(TAXITEMGROUP)
 ,VATNUMJOURNAL = dbo.LP_STR(VATNUMJOURNAL)
 ,PURCHIDRANGE = dbo.LP_STR(PURCHIDRANGE)
 ,DEL_OCRLINE = dbo.LP_STR(DEL_OCRLINE)
 ,BANKCENTRALBANKPURPOSECODE = dbo.LP_STR(BANKCENTRALBANKPURPOSECODE)
 ,BANKCENTRALBANKPURPOSETEXT = dbo.LP_STR(BANKCENTRALBANKPURPOSETEXT)
 ,CUSTVENDBANKACCOUNTID = dbo.LP_STR(CUSTVENDBANKACCOUNTID)
 ,ASSETBUDGETMODEL = dbo.LP_STR(ASSETBUDGETMODEL)
 ,ASSETID = dbo.LP_STR(ASSETID)
 ,ASSETREFASSETID = dbo.LP_STR(ASSETREFASSETID)
 ,PROJTAXGROUPSALES = dbo.LP_STR(PROJTAXGROUPSALES)
 ,PROJTAXITEMGROUPSALES = dbo.LP_STR(PROJTAXITEMGROUPSALES)
 ,ERRORCODEPAYMENT = dbo.LP_STR(ERRORCODEPAYMENT)
 ,ASSETBOOKID = dbo.LP_STR(ASSETBOOKID)
 ,BANKREMITTANCEFILEID = dbo.LP_STR(BANKREMITTANCEFILEID)
 ,BANKACCOUNTID = dbo.LP_STR(BANKACCOUNTID)
 ,BANKPROMISSORYNOTENUM = dbo.LP_STR(BANKPROMISSORYNOTENUM)
 ,PROJEMPLID = dbo.LP_STR(PROJEMPLID)
 ,DEL_PAYMITEMCODEID = dbo.LP_STR(DEL_PAYMITEMCODEID)
 ,BANKBILLOFEXCHANGENUM = dbo.LP_STR(BANKBILLOFEXCHANGENUM)
 ,NEGINSTID = dbo.LP_STR(NEGINSTID)
 ,TAXWITHHOLDGROUP = dbo.LP_STR(TAXWITHHOLDGROUP)
 ,DC_CONTRACTID = dbo.LP_STR(DC_CONTRACTID)
 ,DC_VENDAPPROVEID = dbo.LP_STR(DC_VENDAPPROVEID)
 ,MODIFIEDBY = dbo.LP_STR(MODIFIEDBY)
 ,CREATEDBY = dbo.LP_STR(CREATEDBY)
 ,DATAAREAID = dbo.LP_STR(DATAAREAID)
GO
DROP VIEW Tmp_ViewLEDGERJOURNALTRANS
DROP VIEW Tmp_ViewLEDGERJOURNALTRANS_ORA
drop table dbo.TMP_LEDGERJOURNALTRANS
GO
select * into AX40_KNI_DRIFT.dbo.TMP_LEDGERJOURNALTRANS
FROM OPENQUERY(S2AX40TEST, 'SELECT 
 JOURNALNUM
 ,TO_CHAR(LINENUM) as LINENUM
 ,TO_CHAR(ACCOUNTTYPE) as ACCOUNTTYPE
 ,ACCOUNTNUM
 ,COMPANY
 ,TXT
 ,TO_CHAR(AMOUNTCURDEBIT) as AMOUNTCURDEBIT
 ,CURRENCYCODE
 ,TO_CHAR(EXCHRATE) as EXCHRATE
 ,TAXGROUP
 ,TO_CHAR(QTY) as QTY
 ,DIMENSION
 ,DIMENSION2_
 ,DIMENSION3_
 ,BANKNEGINSTRECIPIENTNAME
 ,TO_CHAR(POSTDATEDCHECK_MY) as POSTDATEDCHECK_MY
 ,TO_CHAR(PRICE) as PRICE
 ,DEL_CORRECTIVEREASON
 ,DEL_CORRECTEDINVOICEID
 ,TO_CHAR(INTERCODIMENSION) as INTERCODIMENSION
 ,TO_CHAR(INTERCODIMENSION2_) as INTERCODIMENSION2_
 ,TO_CHAR(INTERCODIMENSION3_) as INTERCODIMENSION3_
 ,TO_CHAR(SETTLEVOUCHER) as SETTLEVOUCHER
 ,POSTINGPROFILE
 ,VOUCHER
 ,TO_CHAR(AMOUNTCURCREDIT) as AMOUNTCURCREDIT
 ,TO_CHAR(PAYMENTSTATUS) as PAYMENTSTATUS
 ,TO_CHAR(CASHDISCAMOUNT) as CASHDISCAMOUNT
 ,TO_CHAR(VENDTRANSID) as VENDTRANSID
 ,TO_CHAR(CUSTTRANSID) as CUSTTRANSID
 ,TO_CHAR(REMAINAMOUNT) as REMAINAMOUNT
 ,TAXCODE
 ,OFFSETACCOUNT
 ,TO_CHAR(BANKDEPOSITVOUCHER) as BANKDEPOSITVOUCHER
 ,PAYMREFERENCE
 ,BANKDEPOSITNUM
 ,PAYMSPEC
 ,PAYMMODE
 ,TO_CHAR(OFFSETACCOUNTTYPE) as OFFSETACCOUNTTYPE
 ,BANKTRANSTYPE
 ,OFFSETCOMPANY
 ,OFFSETTXT
 ,PAYMENTNOTES
 ,FOREIGNVOUCHER
 ,FOREIGNCOMPANY
 ,TO_CHAR(DEL_FOREIGNTAX) as DEL_FOREIGNTAX
 ,TO_CHAR(TRANSFERRED) as TRANSFERRED
 ,TO_CHAR(CANCEL) as CANCEL
 ,TO_CHAR(NOEDIT) as NOEDIT
 ,TO_CHAR(INVISIBLE) as INVISIBLE
 ,TRANSDATE
 ,TO_CHAR(TRANSACTIONTYPE) as TRANSACTIONTYPE
 ,DOCUMENTDATE
 ,DOCUMENTNUM
 ,TO_CHAR(APPROVED) as APPROVED
 ,APPROVEDBY
 ,PAYMID
 ,TO_CHAR(FREQVALUE) as FREQVALUE
 ,TO_CHAR(FREQCODE) as FREQCODE
 ,DUE
 ,DATECASHDISC
 ,TRANSFERREDBY
 ,LOADINGDATE
 ,FILECREATED
 ,PAYMENTACCOUNT
 ,INVOICE
 ,TRANSFERREDTO
 ,TO_CHAR(TRANSFER) as TRANSFER
 ,LASTTRANSFERRED
 ,TRANSFERREDON
 ,TO_CHAR(PURCHLEDGERPOSTING) as PURCHLEDGERPOSTING
 ,BANKCHEQUENUM
 ,PAYMENT
 ,CASHDISCCODE
 ,TO_CHAR(EXCHRATESECOND) as EXCHRATESECOND
 ,TO_CHAR(TRIANGULATION) as TRIANGULATION
 ,TAXITEMGROUP
 ,VATNUMJOURNAL
 ,TO_CHAR(LISTCODE) as LISTCODE
 ,TO_CHAR(FURTHERPOSTINGTYPE) as FURTHERPOSTINGTYPE
 ,PURCHIDRANGE
 ,TO_CHAR(POOLRECID) as POOLRECID
 ,TO_CHAR(PREPAYMENT) as PREPAYMENT
 ,IMPORTDATE
 ,DEL_OCRLINE
 ,BANKCENTRALBANKPURPOSECODE
 ,BANKCENTRALBANKPURPOSETEXT
 ,CUSTVENDBANKACCOUNTID
 ,TO_CHAR(PAYMENTSEQUENCENUM) as PAYMENTSEQUENCENUM
 ,TO_CHAR(ASSETTRANSTYPE) as ASSETTRANSTYPE
 ,TO_CHAR(DEL_ASSETTOFROMRECID) as DEL_ASSETTOFROMRECID
 ,ASSETBUDGETMODEL
 ,ASSETID
 ,TO_CHAR(ASSETBUDGETPOSTINGSTATUS) as ASSETBUDGETPOSTINGSTATUS
 ,TO_CHAR(ASSETDEPRECIATIONTIME) as ASSETDEPRECIATIONTIME
 ,ASSETREFASSETID
 ,PROJTAXGROUPSALES
 ,PROJTAXITEMGROUPSALES
 ,ERRORCODEPAYMENT
 ,TO_CHAR(FURTHERPOSTINGRECID) as FURTHERPOSTINGRECID
 ,TO_CHAR(TAXDIRECTIONCONTROL) as TAXDIRECTIONCONTROL
 ,TO_CHAR(RESERVETRANSID) as RESERVETRANSID
 ,TO_CHAR(DEL_ASSETSECTION179TRANS) as DEL_ASSETSECTION179TRANS
 ,TO_CHAR(ASSETREVALUATIONAMOUNT) as ASSETREVALUATIONAMOUNT
 ,TO_CHAR(ASSETREVALUATIONTRANS) as ASSETREVALUATIONTRANS
 ,TO_CHAR(ASSETCONSUMPTIONQTY) as ASSETCONSUMPTIONQTY
 ,ASSETBOOKID
 ,TO_CHAR(CUSTVENDNEGINSTPROTESTREASON) as CUSTVENDNEGINSTPROTESTREASON
 ,TO_CHAR(BANKREMITTANCETYPE) as BANKREMITTANCETYPE
 ,BANKREMITTANCEFILEID
 ,BANKACCOUNTID
 ,BANKPROMISSORYNOTENUM
 ,PROJEMPLID
 ,DEL_PAYMITEMCODEID
 ,BANKBILLOFEXCHANGENUM
 ,NEGINSTID
 ,TAXWITHHOLDGROUP
 ,DC_CONTRACTID
 ,TO_CHAR(DC_CONTRACTVERSION) as DC_CONTRACTVERSION
 ,DC_VENDAPPROVEID
 ,MODIFIEDDATE
 ,TO_CHAR(MODIFIEDTIME) as MODIFIEDTIME
 ,MODIFIEDBY
 ,CREATEDDATE
 ,TO_CHAR(CREATEDTIME) as CREATEDTIME
 ,CREATEDBY
 ,DATAAREAID
 ,TO_CHAR(RECVERSION) as RECVERSION
 ,TO_CHAR(RECID) as RECID
 FROM dbo.LEDGERJOURNALTRANS WHERE SUBSTR(NLS_LOWER(DATAAREAID),1,7) = ''kni''')
 
GO
CREATE VIEW TMP_ViewLEDGERJOURNALTRANS AS
 select 
 JOURNALNUM
 ,LINENUM
 ,ACCOUNTTYPE
 ,ACCOUNTNUM
 ,COMPANY
 ,TXT
 ,AMOUNTCURDEBIT
 ,CURRENCYCODE
 ,EXCHRATE
 ,TAXGROUP
 ,QTY
 ,DIMENSION
 ,DIMENSION2_
 ,DIMENSION3_
 ,BANKNEGINSTRECIPIENTNAME
 ,POSTDATEDCHECK_MY
 ,PRICE
 ,DEL_CORRECTIVEREASON
 ,DEL_CORRECTEDINVOICEID
 ,INTERCODIMENSION
 ,INTERCODIMENSION2_
 ,INTERCODIMENSION3_
 ,SETTLEVOUCHER
 ,POSTINGPROFILE
 ,VOUCHER
 ,AMOUNTCURCREDIT
 ,PAYMENTSTATUS
 ,CASHDISCAMOUNT
 ,VENDTRANSID
 ,CUSTTRANSID
 ,REMAINAMOUNT
 ,TAXCODE
 ,OFFSETACCOUNT
 ,BANKDEPOSITVOUCHER
 ,PAYMREFERENCE
 ,BANKDEPOSITNUM
 ,PAYMSPEC
 ,PAYMMODE
 ,OFFSETACCOUNTTYPE
 ,BANKTRANSTYPE
 ,OFFSETCOMPANY
 ,OFFSETTXT
 ,PAYMENTNOTES
 ,FOREIGNVOUCHER
 ,FOREIGNCOMPANY
 ,DEL_FOREIGNTAX
 ,TRANSFERRED
 ,CANCEL
 ,NOEDIT
 ,INVISIBLE
 ,TRANSDATE
 ,TRANSACTIONTYPE
 ,DOCUMENTDATE
 ,DOCUMENTNUM
 ,APPROVED
 ,APPROVEDBY
 ,PAYMID
 ,FREQVALUE
 ,FREQCODE
 ,DUE
 ,DATECASHDISC
 ,TRANSFERREDBY
 ,LOADINGDATE
 ,FILECREATED
 ,PAYMENTACCOUNT
 ,INVOICE
 ,TRANSFERREDTO
 ,TRANSFER
 ,LASTTRANSFERRED
 ,TRANSFERREDON
 ,PURCHLEDGERPOSTING
 ,BANKCHEQUENUM
 ,PAYMENT
 ,CASHDISCCODE
 ,EXCHRATESECOND
 ,TRIANGULATION
 ,TAXITEMGROUP
 ,VATNUMJOURNAL
 ,LISTCODE
 ,FURTHERPOSTINGTYPE
 ,PURCHIDRANGE
 ,POOLRECID
 ,PREPAYMENT
 ,IMPORTDATE
 ,DEL_OCRLINE
 ,BANKCENTRALBANKPURPOSECODE
 ,BANKCENTRALBANKPURPOSETEXT
 ,CUSTVENDBANKACCOUNTID
 ,PAYMENTSEQUENCENUM
 ,ASSETTRANSTYPE
 ,DEL_ASSETTOFROMRECID
 ,ASSETBUDGETMODEL
 ,ASSETID
 ,ASSETBUDGETPOSTINGSTATUS
 ,ASSETDEPRECIATIONTIME
 ,ASSETREFASSETID
 ,PROJTAXGROUPSALES
 ,PROJTAXITEMGROUPSALES
 ,ERRORCODEPAYMENT
 ,FURTHERPOSTINGRECID
 ,TAXDIRECTIONCONTROL
 ,RESERVETRANSID
 ,DEL_ASSETSECTION179TRANS
 ,ASSETREVALUATIONAMOUNT
 ,ASSETREVALUATIONTRANS
 ,ASSETCONSUMPTIONQTY
 ,ASSETBOOKID
 ,CUSTVENDNEGINSTPROTESTREASON
 ,BANKREMITTANCETYPE
 ,BANKREMITTANCEFILEID
 ,BANKACCOUNTID
 ,BANKPROMISSORYNOTENUM
 ,PROJEMPLID
 ,DEL_PAYMITEMCODEID
 ,BANKBILLOFEXCHANGENUM
 ,NEGINSTID
 ,TAXWITHHOLDGROUP
 ,DC_CONTRACTID
 ,DC_CONTRACTVERSION
 ,DC_VENDAPPROVEID
 ,MODIFIEDDATE
 ,MODIFIEDTIME
 ,MODIFIEDBY
 ,CREATEDDATE
 ,CREATEDTIME
 ,CREATEDBY
 ,DATAAREAID
 ,RECVERSION
 ,RECID
 from dbo.LEDGERJOURNALTRANS
GO
 
CREATE VIEW TMP_ViewLEDGERJOURNALTRANS_ORA AS
select
 JOURNALNUM
 ,CAST(LINENUM as real) AS LINENUM
 ,CAST(ACCOUNTTYPE as int) AS ACCOUNTTYPE
 ,ACCOUNTNUM
 ,COMPANY
 ,TXT
 ,CAST(AMOUNTCURDEBIT as real) AS AMOUNTCURDEBIT
 ,CURRENCYCODE
 ,CAST(EXCHRATE as real) AS EXCHRATE
 ,TAXGROUP
 ,CAST(QTY as real) AS QTY
 ,DIMENSION
 ,DIMENSION2_
 ,DIMENSION3_
 ,BANKNEGINSTRECIPIENTNAME
 ,CAST(POSTDATEDCHECK_MY as int) AS POSTDATEDCHECK_MY
 ,CAST(PRICE as real) AS PRICE
 ,DEL_CORRECTIVEREASON
 ,DEL_CORRECTEDINVOICEID
 ,CAST(INTERCODIMENSION as int) AS INTERCODIMENSION
 ,CAST(INTERCODIMENSION2_ as int) AS INTERCODIMENSION2_
 ,CAST(INTERCODIMENSION3_ as int) AS INTERCODIMENSION3_
 ,CAST(SETTLEVOUCHER as int) AS SETTLEVOUCHER
 ,POSTINGPROFILE
 ,VOUCHER
 ,CAST(AMOUNTCURCREDIT as real) AS AMOUNTCURCREDIT
 ,CAST(PAYMENTSTATUS as int) AS PAYMENTSTATUS
 ,CAST(CASHDISCAMOUNT as real) AS CASHDISCAMOUNT
 ,CAST(VENDTRANSID as bigint) AS VENDTRANSID
 ,CAST(CUSTTRANSID as bigint) AS CUSTTRANSID
 ,CAST(REMAINAMOUNT as real) AS REMAINAMOUNT
 ,TAXCODE
 ,OFFSETACCOUNT
 ,CAST(BANKDEPOSITVOUCHER as int) AS BANKDEPOSITVOUCHER
 ,PAYMREFERENCE
 ,BANKDEPOSITNUM
 ,PAYMSPEC
 ,PAYMMODE
 ,CAST(OFFSETACCOUNTTYPE as int) AS OFFSETACCOUNTTYPE
 ,BANKTRANSTYPE
 ,OFFSETCOMPANY
 ,OFFSETTXT
 ,PAYMENTNOTES
 ,FOREIGNVOUCHER
 ,FOREIGNCOMPANY
 ,CAST(DEL_FOREIGNTAX as int) AS DEL_FOREIGNTAX
 ,CAST(TRANSFERRED as int) AS TRANSFERRED
 ,CAST(CANCEL as int) AS CANCEL
 ,CAST(NOEDIT as int) AS NOEDIT
 ,CAST(INVISIBLE as int) AS INVISIBLE
 ,TRANSDATE
 ,CAST(TRANSACTIONTYPE as int) AS TRANSACTIONTYPE
 ,DOCUMENTDATE
 ,DOCUMENTNUM
 ,CAST(APPROVED as int) AS APPROVED
 ,APPROVEDBY
 ,PAYMID
 ,CAST(FREQVALUE as int) AS FREQVALUE
 ,CAST(FREQCODE as int) AS FREQCODE
 ,DUE
 ,DATECASHDISC
 ,TRANSFERREDBY
 ,LOADINGDATE
 ,FILECREATED
 ,PAYMENTACCOUNT
 ,INVOICE
 ,TRANSFERREDTO
 ,CAST(TRANSFER as int) AS TRANSFER
 ,LASTTRANSFERRED
 ,TRANSFERREDON
 ,CAST(PURCHLEDGERPOSTING as int) AS PURCHLEDGERPOSTING
 ,BANKCHEQUENUM
 ,PAYMENT
 ,CASHDISCCODE
 ,CAST(EXCHRATESECOND as real) AS EXCHRATESECOND
 ,CAST(TRIANGULATION as int) AS TRIANGULATION
 ,TAXITEMGROUP
 ,VATNUMJOURNAL
 ,CAST(LISTCODE as int) AS LISTCODE
 ,CAST(FURTHERPOSTINGTYPE as int) AS FURTHERPOSTINGTYPE
 ,PURCHIDRANGE
 ,CAST(POOLRECID as bigint) AS POOLRECID
 ,CAST(PREPAYMENT as int) AS PREPAYMENT
 ,IMPORTDATE
 ,DEL_OCRLINE
 ,BANKCENTRALBANKPURPOSECODE
 ,BANKCENTRALBANKPURPOSETEXT
 ,CUSTVENDBANKACCOUNTID
 ,CAST(PAYMENTSEQUENCENUM as int) AS PAYMENTSEQUENCENUM
 ,CAST(ASSETTRANSTYPE as int) AS ASSETTRANSTYPE
 ,CAST(DEL_ASSETTOFROMRECID as bigint) AS DEL_ASSETTOFROMRECID
 ,ASSETBUDGETMODEL
 ,ASSETID
 ,CAST(ASSETBUDGETPOSTINGSTATUS as int) AS ASSETBUDGETPOSTINGSTATUS
 ,CAST(ASSETDEPRECIATIONTIME as real) AS ASSETDEPRECIATIONTIME
 ,ASSETREFASSETID
 ,PROJTAXGROUPSALES
 ,PROJTAXITEMGROUPSALES
 ,ERRORCODEPAYMENT
 ,CAST(FURTHERPOSTINGRECID as bigint) AS FURTHERPOSTINGRECID
 ,CAST(TAXDIRECTIONCONTROL as int) AS TAXDIRECTIONCONTROL
 ,CAST(RESERVETRANSID as bigint) AS RESERVETRANSID
 ,CAST(DEL_ASSETSECTION179TRANS as int) AS DEL_ASSETSECTION179TRANS
 ,CAST(ASSETREVALUATIONAMOUNT as real) AS ASSETREVALUATIONAMOUNT
 ,CAST(ASSETREVALUATIONTRANS as int) AS ASSETREVALUATIONTRANS
 ,CAST(ASSETCONSUMPTIONQTY as real) AS ASSETCONSUMPTIONQTY
 ,ASSETBOOKID
 ,CAST(CUSTVENDNEGINSTPROTESTREASON as int) AS CUSTVENDNEGINSTPROTESTREASON
 ,CAST(BANKREMITTANCETYPE as int) AS BANKREMITTANCETYPE
 ,BANKREMITTANCEFILEID
 ,BANKACCOUNTID
 ,BANKPROMISSORYNOTENUM
 ,PROJEMPLID
 ,DEL_PAYMITEMCODEID
 ,BANKBILLOFEXCHANGENUM
 ,NEGINSTID
 ,TAXWITHHOLDGROUP
 ,DC_CONTRACTID
 ,CAST(DC_CONTRACTVERSION as int) AS DC_CONTRACTVERSION
 ,DC_VENDAPPROVEID
 ,MODIFIEDDATE
 ,CAST(MODIFIEDTIME as int) AS MODIFIEDTIME
 ,MODIFIEDBY
 ,CREATEDDATE
 ,CAST(CREATEDTIME as int) AS CREATEDTIME
 ,CREATEDBY
 ,DATAAREAID
 ,CAST(RECVERSION as int) AS RECVERSION
 ,CAST(RECID as bigint) AS RECID
from dbo.TMP_LEDGERJOURNALTRANS
GO
delete from TMP_ViewLEDGERJOURNALTRANS where dataareaid = 'KNI'
insert into TMP_ViewLEDGERJOURNALTRANS select * from TMP_ViewLEDGERJOURNALTRANS_ORA