if OBJECT_ID('LP_CustStat_a','V') is not null
begin
	drop view LP_CustStat_a
end	
GO
create VIEW [dbo].[LP_CustStat_a]
as
SELECT ITable.ITEMID	   + ' ' + ITable.ITEMNAME AS Item, 
	   ITable.ITEMGROUPID  + ' ' + IGrp.NAME  AS ItemGrp,
	   LTRIM(ITrans.CUSTVENDAC) + ' ' + CTable.NAME AS CustAccount,
	   -1 * SUM(ITrans.QTY) AS Qty,
	   CASE WHEN sum(CIT.QTY) <> 0 THEN	((SUM(CIT.LINEAMOUNTMST)+sum(CIT.sumlinediscmst)) 
												*(-1*SUM(ITrans.QTY)/sum(CIT.QTY)))
									ELSE 0
									END		AS SalesAmountMst, 
       CASE WHEN sum(CIT.QTY) <> 0 THEN	sum(CIT.sumlinediscmst) * (-1*SUM(ITrans.QTY)/sum(CIT.QTY))
									 ELSE 0
									 END	AS LineDiscMst,
		(SUM(ITrans.COSTAMOUNTPOSTED) + SUM(ITrans.COSTAMOUNTADJUSTMENT)) * - 1 AS CostAmount,
		CTable.SALESGROUP AS SalesGrp,
		CIT.DIMENSION AS Department, 
		IDim.INVENTLOCATIONID AS InventLocationId,
		LTRIM(ITrans.INVOICEID) AS InvoiceId,
		LEFT(CONVERT(varchar, ITrans.DATEFINANCIAL, 120), 10) AS InvDate, 
		dbo.LP_YEAR_WEEK(ITrans.DATEFINANCIAL) AS InvYrWk, 		
		CIT.DATAAREAID AS DataareaId,
		dbo.LP_App_FiscalYrMth(ITrans.DATEFINANCIAL) as FiscalYrMth,
		dbo.LP_App_FiscalYr(ITrans.DATEFINANCIAL) as FiscalYr,
		CTable.STATISTICSGROUP as StatisticsGroup,
		CTable.zipcode as ZipCode,
		-- CTable.COUNTRYREGIONID as Country, -- 40
		CTable.COUNTRY as Country, --30
		CIJ.LEDGERVOUCHER as LedgerVoucher,
		--ITrans.recid,
		1 AS CNT
                      
FROM CUSTINVOICETRANS CIT INNER JOIN
	CUSTINVOICEJOUR CIJ ON CIJ.DATAAREAID = CIT.DATAAREAID AND CIJ.INVOICEID = CIT.INVOICEID AND CIJ.INVOICEDATE = CIT.INVOICEDATE INNER JOIN
	CUSTTABLE CTable ON CTable.DATAAREAID = CIT.DATAAREAID AND CTable.ACCOUNTNUM = CIJ.ORDERACCOUNT INNER JOIN
	INVENTTABLE ITable ON ITable.ITEMID = CIT.ITEMID AND ITable.DATAAREAID = CIT.DATAAREAID INNER JOIN
	INVENTITEMGROUP IGrp ON IGrp.ITEMGROUPID = ITable.ITEMGROUPID AND IGrp.DATAAREAID = CIT.DATAAREAID INNER JOIN
	INVENTTRANS ITrans ON ITrans.INVENTTRANSID = CIT.INVENTTRANSID AND ITrans.InventDimId = CIT.InventDimId AND ITrans.INVOICEID = CIT.INVOICEID AND ITrans.DATEFINANCIAL = CIT.INVOICEDATE AND ITrans.DATAAREAID = CIT.DATAAREAID INNER JOIN
	INVENTDIM IDim ON IDim.INVENTDIMID = CIT.INVENTDIMID
GROUP BY ITable.ITEMID, ITable.ITEMNAME, ITable.ITEMGROUPID, IGrp.NAME, ITrans.CUSTVENDAC, CTable.NAME, CTable.SALESGROUP,
	CIT.DIMENSION, IDim.INVENTLOCATIONID, ITrans.INVOICEID, ITrans.DATEFINANCIAL, CIT.DATAAREAID, CTable.STATISTICSGROUP, CTable.ZIPCODE,
	CIJ.LEDGERVOUCHER, 
	--CTable.COUNTRYREGIONID --40
	CTable.COUNTRY --30
GO	
select * from 	dbo.LP_CustStat_a