--select top 1000 inventtable.NAMEALIAS,infocodeid,INFORMATION, * from RETAILTRANSACTIONSALESTRANS
select distinct(left(information,13)), (select top 1 itemid from INVENTITEMBARCODE where INVENTITEMBARCODE.ITEMBARCODE = left(information,13))
from RETAILTRANSACTIONSALESTRANS
--select count(*) from RETAILTRANSACTIONSALESTRANS 
join inventtable on
inventtable.itemid = RETAILTRANSACTIONSALESTRANS.itemid
join RETAILTRANSACTIONINFOCODETRANS on
RETAILTRANSACTIONINFOCODETRANS.TRANSACTIONID = RETAILTRANSACTIONSALESTRANS.TRANSACTIONID and
RETAILTRANSACTIONINFOCODETRANS.LINENUM = RETAILTRANSACTIONSALESTRANS.LINENUM
where NAMEALIAS like 'Wert%' and INFOCODEID = 'NoItemFoun' and information not like '%:%' and not exists (select top 1 itemid from INVENTITEMBARCODE where INVENTITEMBARCODE.ITEMBARCODE = left(information,13))
--order by RETAILTRANSACTIONSALESTRANS.transactionId DESC, RETAILTRANSACTIONSALESTRANS.LINENUM DESC