----select distinct(ITEMGROUPID) from INVENTTABLE
----	JOIN INVENTITEMGROUPITEM ON
----	INVENTITEMGROUPITEM.ITEMDATAAREAID = INVENTTABLE.DATAAREAID
----	and INVENTITEMGROUPITEM.itemid = INVENTTABLE.itemid	

--select PURCHTABLE.INVOICEACCOUNT, DIRPARTYTABLE.NAME ,PURCHTABLE.PURCHID, case AP_ITEMOWNERSHIPMODEL when 0 then 'ownbuy' when 3 then 'Konsig' end as HeaderOwnerShipModel, 
--	PURCHLINE.ITEMID, INVENTITEMGROUPITEM.ITEMGROUPID, PURCHLINE.recid PurchLineRecId 
--	from PurchTable
--	join PURCHLINE on
--	PurchLine.PURCHID = PURCHTABLE.PURCHID
--	JOIN INVENTITEMGROUPITEM ON
--	INVENTITEMGROUPITEM.ITEMDATAAREAID = PURCHLINE.DATAAREAID
--	and INVENTITEMGROUPITEM.itemid = PURCHLINE.itemid
--	join VENDTABLE on
--	VENDTABLE.ACCOUNTNUM = Purchtable.INVOICEACCOUNT
--	join DIRPARTYTABLE on  DIRPARTYTABLE.RECID = VENDTABLE.PARTY
--	where ((INVENTITEMGROUPITEM.ITEMGROUPID='Eigenkauf' and PURCHTABLE.AP_ITEMOWNERSHIPMODEL<>0) or
--		(INVENTITEMGROUPITEM.ITEMGROUPID='Konsign' and PURCHTABLE.AP_ITEMOWNERSHIPMODEL<>3))
--	order by PURCHID

--select PURCHTABLE.INVOICEACCOUNT, DIRPARTYTABLE.NAME ,PURCHTABLE.PURCHID, case AP_ITEMOWNERSHIPMODEL when 0 then 'ownbuy' when 3 then 'Konsig' end as HeaderOwnerShipModel, 
--	PURCHLINE.ITEMID, INVENTITEMGROUPITEM.ITEMGROUPID, PURCHLINE.recid PurchLineRecId 
update PurchTable set AP_ITEMOWNERSHIPMODEL = (case ITEMGROUPID when 'Eigenkauf' then 0 when 'Konsign' then 3 end)
	from PurchTable
	join PURCHLINE on
	PurchLine.PURCHID = PURCHTABLE.PURCHID
	JOIN INVENTITEMGROUPITEM ON
	INVENTITEMGROUPITEM.ITEMDATAAREAID = PURCHLINE.DATAAREAID
	and INVENTITEMGROUPITEM.itemid = PURCHLINE.itemid
	join VENDTABLE on
	VENDTABLE.ACCOUNTNUM = Purchtable.INVOICEACCOUNT
	join DIRPARTYTABLE on  DIRPARTYTABLE.RECID = VENDTABLE.PARTY
	where ((INVENTITEMGROUPITEM.ITEMGROUPID='Eigenkauf' and PURCHTABLE.AP_ITEMOWNERSHIPMODEL<>0) or
		(INVENTITEMGROUPITEM.ITEMGROUPID='Konsign' and PURCHTABLE.AP_ITEMOWNERSHIPMODEL<>3))
	--order by PURCHID
