use axdb_rc20
delete bmssa.sysconfig where configtype>=0 and configtype<=2
go
insert bmssa.sysconfig (configtype, id, value,recid) values (2,0,'HGCC20P',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,1,'EI16A9B',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,2,'E05AIHH',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,3,'AD87DR3',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,4,'GI69PSP',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,5,'EHHMQ0T',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,6,'CBFLLRX',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,7,'BIBF4QO',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,8,'EFA84GX',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,9,'G3BFKP7',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,10,'I55PIJO',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,11,'H5GQNCM',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,16,'FHMCMF6',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,17,'D7FIJGD',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,18,'D93DLEM',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,24,'D2F6HHQ',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,25,'IELJSF0',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,31,'BEGMJ71',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,37,'FII7T61',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (2,38,'II0J53V',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (0,0,'Columbus IT Partner A/S',1)
insert bmssa.sysconfig (configtype, id, value,recid) values (1,0,'99382004',1)