
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[LP_CustStat1]
AS
SELECT     TOP 100 PERCENT dbo.CUSTINVOICETRANS.ITEMID + ' ' + dbo.INVENTTABLE.ITEMNAME AS ITEM, 
					  dbo.INVENTTABLE.ITEMNAME, 
                      dbo.INVENTTABLE.ITEMGROUPID + ' ' +
                          (SELECT     NAME
                            FROM          dbo.INVENTITEMGROUP
                            WHERE      (ITEMGROUPID = dbo.INVENTTABLE.ITEMGROUPID) AND (DATAAREAID = dbo.INVENTTABLE.DATAAREAID)) AS ItemGRP, 
                      LTRIM(dbo.INVENTTRANS.CUSTVENDAC) + ' ' + CUSTTABLE_1.NAME AS CustAccount, 
				      CUSTTABLE_1.NAME AS CustName, 
                      CUSTTABLE_1.CUSTGROUP + ' ' + dbo.CUSTGROUP.NAME AS CustGrp, 
					  dbo.LP_INT(SUM(dbo.CUSTINVOICETRANS.QTY)) AS Qty, 
                      dbo.LP_DECIMAL(SUM(dbo.CUSTINVOICETRANS.LINEAMOUNTMST) - sum(dbo.CUSTINVOICETRANS.sumlinediscmst)) AS SalesAmountMST, 
                      dbo.LP_DECIMAL(sum(dbo.CUSTINVOICETRANS.sumlinediscmst)) AS LinediscMST, 
					  dbo.LP_DECIMAL((SUM(dbo.INVENTTRANS.COSTAMOUNTPOSTED) + SUM(dbo.INVENTTRANS.COSTAMOUNTADJUSTMENT)) * - 1) AS CostAmountPosted, 
					  dbo.CUSTINVOICETRANS.SALESGROUP as SalesGroup, 
                      dbo.CUSTINVOICETRANS.DIMENSION as Department, 
					  LTRIM(dbo.CUSTINVOICETRANS.INVOICEID) AS InvoiceId, 
					  LEFT(CONVERT(varchar, dbo.CUSTINVOICETRANS.INVOICEDATE, 120), 10) AS InvDate, 
					  DATEPART(yyyy, dbo.CUSTINVOICETRANS.INVOICEDATE) AS Yr, 
                      dbo.LP_YEAR_MTH(dbo.CUSTINVOICETRANS.INVOICEDATE) AS YrMth, dbo.LP_YEAR_WEEK(dbo.CUSTINVOICETRANS.INVOICEDATE) AS YrWk, 
                      dbo.LP_DECIMAL((SUM(dbo.CUSTINVOICETRANS.LINEAMOUNTMST) - sum(dbo.CUSTINVOICETRANS.sumlinediscmst)) / 7.4591) AS SalesAmountEUR, 
                      dbo.LP_DECIMAL(SUM(dbo.INVENTTRANS.COSTAMOUNTPOSTED) / - 7.4591) AS CostAmountEUR, 
					  dbo.INVENTTABLE.DATAAREAID as dataareaid, 
					  dbo.LP_MTHNAME(dbo.CUSTINVOICETRANS.INVOICEDATE) AS Mth, 
					  dbo.CUSTINVOICETRANS.LEDGERACCOUNT as Ledgeraccount, 
                      LTRIM(dbo.CUSTINVOICEJOUR.INVOICEACCOUNT) + ' ' +
                          (SELECT     NAME
                            FROM          dbo.CUSTTABLE
                            WHERE      (ACCOUNTNUM = dbo.CUSTINVOICEJOUR.INVOICEACCOUNT) AND (DATAAREAID = dbo.CUSTINVOICETRANS.DATAAREAID)) AS InvoiceAccount,
					  dbo.CUSTINVOICEJOUR.DLVCOUNTRY as DlvCountry,
					  dbo.CUSTINVOICEJOUR.INVCOUNTRY as InvCountry,
					  dbo.LP_App_ICAccount(CUSTTABLE_1.NAME) as ICAccount,
					  dbo.LP_App_FiscalYrMth(dbo.CUSTINVOICETRANS.INVOICEDATE) as FiscalYrMth,
					  dbo.LP_App_FiscalMth(dbo.CUSTINVOICETRANS.INVOICEDATE) as FiscalMth,
					  CUSTTABLE_1.STATISTICSGROUP as StatisticsGroup,
					  CUSTTABLE_1.zipcode as ZipCode,
					  1 AS CNT, 'EOR' AS EOR
FROM         dbo.CUSTINVOICETRANS INNER JOIN
                      dbo.INVENTTRANS ON dbo.CUSTINVOICETRANS.DATAAREAID = dbo.INVENTTRANS.DATAAREAID AND 
                      dbo.CUSTINVOICETRANS.INVENTTRANSID = dbo.INVENTTRANS.INVENTTRANSID INNER JOIN
                      dbo.INVENTTABLE ON dbo.INVENTTRANS.ITEMID = dbo.INVENTTABLE.ITEMID AND 
                      dbo.INVENTTRANS.DATAAREAID = dbo.INVENTTABLE.DATAAREAID INNER JOIN
                      dbo.CUSTTABLE AS CUSTTABLE_1 ON dbo.CUSTINVOICETRANS.DATAAREAID = CUSTTABLE_1.DATAAREAID AND 
                      dbo.INVENTTRANS.CUSTVENDAC = CUSTTABLE_1.ACCOUNTNUM INNER JOIN
                      dbo.CUSTGROUP ON CUSTTABLE_1.DATAAREAID = dbo.CUSTGROUP.DATAAREAID AND 
                      CUSTTABLE_1.CUSTGROUP = dbo.CUSTGROUP.CUSTGROUP INNER JOIN
                      dbo.CUSTINVOICEJOUR ON dbo.CUSTINVOICETRANS.INVOICEDATE = dbo.CUSTINVOICEJOUR.INVOICEDATE AND 
                      dbo.CUSTINVOICETRANS.INVOICEID = dbo.CUSTINVOICEJOUR.INVOICEID AND 
                      dbo.CUSTINVOICETRANS.DATAAREAID = dbo.CUSTINVOICEJOUR.DATAAREAID AND dbo.CUSTINVOICETRANS.DATAAREAID <> 'å2' AND 
                      dbo.CUSTINVOICETRANS.DATAAREAID <> 'åp1'
GROUP BY dbo.CUSTINVOICETRANS.ITEMID, dbo.CUSTINVOICETRANS.DIMENSION, dbo.CUSTINVOICETRANS.INVOICEID, 
                      dbo.CUSTINVOICETRANS.INVOICEDATE, dbo.CUSTINVOICETRANS.SALESGROUP, dbo.INVENTTABLE.ITEMNAME, dbo.INVENTTABLE.ITEMGROUPID, 
                      dbo.INVENTTRANS.CUSTVENDAC, CUSTTABLE_1.NAME, LTRIM(dbo.CUSTINVOICETRANS.INVOICEID), CUSTTABLE_1.CUSTGROUP, 
                      dbo.CUSTGROUP.NAME, dbo.INVENTTABLE.DATAAREAID, dbo.CUSTINVOICETRANS.DATAAREAID, dbo.CUSTINVOICETRANS.LEDGERACCOUNT, 
                      dbo.CUSTINVOICEJOUR.INVOICEACCOUNT,dbo.CUSTINVOICEJOUR.DLVCOUNTRY,CUSTTABLE_1.STATISTICSGROUP,dbo.CUSTINVOICEJOUR.INVCOUNTRY,
					  CUSTTABLE_1.zipcode 
                      
ORDER BY dbo.CUSTINVOICETRANS.ITEMID, dbo.CUSTINVOICETRANS.INVOICEDATE
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO

