SELECT     INVENTITEMGROUP.ITEMGROUPID AS ItemGroup, INVENTITEMGROUP.NAME AS ItemGroupName, INVENTTABLE.ITEMID, INVENTTABLE.ITEMNAME, 
                      CUSTGROUP.CUSTGROUP, CUSTGROUP.NAME AS CustGroupName, CUSTTABLE.ACCOUNTNUM, CUSTTABLE.NAME AS CustName, 
                      INVENTTRANS.COSTAMOUNTPOSTED, INVENTTRANS.STATUSISSUE, CUSTINVOICETRANS.QTY, CUSTINVOICETRANS.LINEAMOUNT, 
                      CUSTINVOICETRANS.LINEAMOUNT * CUSTINVOICEJOUR.EXCHRATE AS LineAmountMST, CUSTINVOICETRANS.DIMENSION AS Dept, 
                      CUSTINVOICETRANS.DIMENSION2_ AS Costcenter, CUSTINVOICETRANS.DIMENSION3_ AS purpose, CUSTINVOICETRANS.SALESID, 
                      CUSTINVOICETRANS.SALESGROUP, CUSTINVOICETRANS.SUMLINEDISCMST, CUSTINVOICEJOUR.INVOICEACCOUNT, CUSTINVOICEJOUR.ORDERACCOUNT
FROM         CUSTINVOICETRANS INNER JOIN
                      CUSTTABLE ON CUSTINVOICETRANS.DATAAREAID = CUSTTABLE.DATAAREAID INNER JOIN
                      INVENTTABLE ON CUSTINVOICETRANS.ITEMID = INVENTTABLE.ITEMID INNER JOIN
                      INVENTITEMGROUP ON CUSTINVOICETRANS.DATAAREAID = INVENTITEMGROUP.DATAAREAID AND 
                      INVENTTABLE.ITEMGROUPID = INVENTITEMGROUP.ITEMGROUPID INNER JOIN
                      CUSTGROUP ON CUSTINVOICETRANS.DATAAREAID = CUSTGROUP.DATAAREAID AND CUSTTABLE.CUSTGROUP = CUSTGROUP.CUSTGROUP INNER JOIN
                      CUSTINVOICEJOUR ON CUSTINVOICETRANS.DATAAREAID = CUSTINVOICEJOUR.DATAAREAID AND 
                      CUSTINVOICETRANS.INVOICEID = CUSTINVOICEJOUR.INVOICEID AND CUSTINVOICETRANS.INVOICEDATE = CUSTINVOICEJOUR.INVOICEDATE INNER JOIN
                      INVENTTRANS ON CUSTINVOICETRANS.INVENTTRANSID = INVENTTRANS.INVENTTRANSID AND INVENTTABLE.ITEMID = INVENTTRANS.ITEMID
WHERE     (INVENTTRANS.STATUSISSUE = 1)

