--delete from REQPROCESSITEMTRACE where PROCESSID = 620714
drop table REQPROCESSITEMDIMLIST
drop table REQPROCESSITEMTRACE 
drop table REQPROCESSITEMLIST
drop table REQPROCESSITEMLISTLINE

--DBCC SHRINKDATABASE (axdb_hct, 10,TRUNCATEONLY);
--select COUNT(*) from REQPROCESSLIST
--select COUNT(*) from REQPROCESSTHREADLIST
--select COUNT(*) from REQPROCESSTHREADLOG
--select COUNT(*) from REQPROCESSPLANNEDORDERLIST

BACKUP LOG axdb_hct TO DISK = 'e:\mssql\backup\backuplog_20130413.bak'
DBCC SHRINKDATABASE (axdb_hct, 10);
