select 'REQPROCESSLIST',COUNT(*) from REQPROCESSLIST where PROCESSID < '761995'
select 'REQPROCESSItemLIST',COUNT(*) from REQPROCESSItemLIST where PROCESSID < '761995'
select 'REQPROCESSItemLISTLine',COUNT(*) from REQPROCESSITEMLISTLINE where PROCESSID < '761995'

select 'REQPROCESSLIST',* from REQPROCESSLIST
delete from REQPROCESSLIST where PROCESSID < '761995'
delete from REQPROCESSItemLIST where PROCESSID < '761995'
delete from REQPROCESSITEMLISTLINE where PROCESSID < '761995'


