SELECT     TOP (30) bmssa.CUSTTABLE.ACCOUNTNUM, bmssa.CUSTTABLE.NAME, /*bmssa.PROJTABLE.PROJID, bmssa.PROJTABLE.NAME AS Expr1, 
                      bmssa.PROJCERTIFICATE.CERTIFICATEID, bmssa.PROJCERTIFICATE.ITEMID,*/ bmssa.PROJCERTIFICATE.CERTTYPE, 
					  CASE bmssa.PROJCERTIFICATE.FORTSTATUS WHEN 0 THEN 'Active' WHEN 1 THEN 'Deleted' ELSE 'Blank' END AS Fortstatus,
				      count(*) as Cnt
FROM         bmssa.CUSTTABLE INNER JOIN
                      bmssa.PROJINVOICETABLE ON bmssa.CUSTTABLE.ACCOUNTNUM = bmssa.PROJINVOICETABLE.INVOICEACCOUNT INNER JOIN
                      bmssa.PROJTABLE ON bmssa.PROJINVOICETABLE.PROJINVOICEPROJID = bmssa.PROJTABLE.PROJINVOICEPROJID INNER JOIN
                      bmssa.PROJCERTIFICATE ON bmssa.PROJTABLE.PROJID = bmssa.PROJCERTIFICATE.PROJID
WHERE		bmssa.PROJCERTIFICATE.FORTSTATUS = 0
GROUP BY bmssa.CUSTTABLE.ACCOUNTNUM, bmssa.CUSTTABLE.NAME, /*bmssa.PROJTABLE.PROJID, bmssa.PROJTABLE.NAME, bmssa.PROJCERTIFICATE.CERTIFICATEID, 
                      bmssa.PROJCERTIFICATE.ITEMID,*/ bmssa.PROJCERTIFICATE.CERTTYPE, bmssa.PROJCERTIFICATE.FORTSTATUS
ORDER BY Cnt DESC
