USE axdb25_HCT
DELETE FROM dbo.SYSIMAGETABLE where recid < 20000
GO
DROP INDEX dbo.SYSIMAGETABLE.I_843NAMELANGUAGETHEMEIDX
GO
CREATE UNIQUE  INDEX I_843NAMELANGUAGETHEMEIDX ON SYSIMAGETABLE(NAME,LANGUAGE,THEME)
GO
DELETE FROM dbo.languagetable where recid < 20000
GO
DROP INDEX dbo.languagetable.I_799KEY
GO
CREATE UNIQUE  INDEX I_799KEY ON dbo.LANGUAGETABLE(LANGUAGEID)
GO
DROP INDEX dbo.USERGROUPINFO.I_65530ID
GO
DELETE FROM dbo.USERGROUPINFO where recid < 20000
GO
CREATE UNIQUE CLUSTERED INDEX I_65530ID ON dbo.USERGROUPINFO(ID)
GO
DROP INDEX dbo.ACCESSRIGHTSLIST.I_65526GROUP
GO
DELETE FROM dbo.ACCESSRIGHTSLIST where recid < 20000
GO
CREATE UNIQUE CLUSTERED INDEX I_65526GROUP ON dbo.ACCESSRIGHTSLIST(GROUPID,DOMAINID,RECORDTYPE,PARENTID,ID) 
GO
DROP INDEX dbo.DATAAREA.I_65533ID
GO
DELETE FROM dbo.DATAAREA where recid < 20000
GO
CREATE UNIQUE CLUSTERED INDEX I_65533ID ON dbo.DATAAREA(ID)
