select count(*) from ax30_procon.dbo.custtable
go
use ax30_procon
drop view dbo.CT_ImportSpecific
go
create view dbo.CT_ImportSpecific as 
select ACCOUNTNUM, NAME, ADDRESS, PHONE, TELEFAX, INVOICEACCOUNT, CUSTGROUP, LINEDISC, PAYMTERMID, CASHDISC, CURRENCY, BLOCKED, 
                      ONETIMECUSTOMER, ACCOUNTSTATEMENT, CREDITMAX, MANDATORYCREDITLIMIT, DIMENSION, DIMENSION2_, DIMENSION3_, VENDACCOUNT, 
                      TELEX, PRICEGROUP, MULTILINEDISC, ENDDISC, VATNUM, COUNTRY, INVENTLOCATION, DLVTERM, DLVMODE, CLEARINGPERIOD, ZIPCODE, 
                      STATE, COUNTY, URL, EMAIL, CELLULARPHONE, PHONELOCAL, FREIGHTZONE, CREDITRATING, TAXGROUP, STATISTICSGROUP, PAYMMODE, 
                      BANKACCOUNT, NAMEALIAS, CONTACTPERSONID, INVOICEADDRESS, OURACCOUNTNUM, SALESPOOLID, INCLTAX, CUSTITEMGROUPID, 
                      NUMBERSEQUENCEGROUP, LANGUAGEID, PAYMDAYID, LINEOFBUSINESSID, DESTINATIONCODEID, SUPPITEMGROUPID, TAXLICENSENUM, 
                      WEBSALESORDERDISPLAY, PAYMSPEC, BANKCENTRALBANKPURPOSETEXT, BANKCENTRALBANKPURPOSECODE, PRINTMODULETYPE, CITY, 
                      STREET, PAGER, SMS, RECID from dbo.custtable
go
use ax30_procon
declare @NewRecid as int
declare @count as int
select @count = count(*) from ax30_develop.dbo.custtable

UPDATE dbo.SystemSequences
    SET    @NewRecid  = NextVal-1,
           NextVal    = NextVal + @Count
	WHERE ID = -1 AND TABID = 0 AND Dataareaid = 'dat'

insert into ax30_procon.dbo.CT_ImportSpecific
	select ACCOUNTNUM, NAME, ADDRESS, PHONE, TELEFAX, INVOICEACCOUNT, CUSTGROUP, LINEDISC, PAYMTERMID, CASHDISC, CURRENCY, BLOCKED, 
                      ONETIMECUSTOMER, ACCOUNTSTATEMENT, CREDITMAX, MANDATORYCREDITLIMIT, DIMENSION, DIMENSION2_, 'FromRGS',VENDACCOUNT, 
                      TELEX, PRICEGROUP, MULTILINEDISC, ENDDISC, VATNUM, COUNTRY, INVENTLOCATION, DLVTERM, DLVMODE, CLEARINGPERIOD, ZIPCODE, 
                      STATE, COUNTY, URL, EMAIL, CELLULARPHONE, PHONELOCAL, FREIGHTZONE, CREDITRATING, TAXGROUP, STATISTICSGROUP, PAYMMODE, 
                      BANKACCOUNT, NAMEALIAS, CONTACTPERSONID, INVOICEADDRESS, OURACCOUNTNUM, SALESPOOLID, INCLTAX, CUSTITEMGROUPID, 
                      NUMBERSEQUENCEGROUP, LANGUAGEID, PAYMDAYID, LINEOFBUSINESSID, DESTINATIONCODEID, SUPPITEMGROUPID, TAXLICENSENUM, 
                      WEBSALESORDERDISPLAY, PAYMSPEC, BANKCENTRALBANKPURPOSETEXT, BANKCENTRALBANKPURPOSECODE, PRINTMODULETYPE, CITY, 
                      STREET, PAGER, SMS, 
					  @NewRecid = @NewRecid + 1,
					  cast(@NewRecid as varchar(10)) as recid from ax30_develop.dbo.custtable
		where DIMENSION3_ = 'FromRGS'
go
select count(*) from ax30_develop.dbo.custtable
--select count(*),custgroup from ax30_develop.dbo.custtable group by custgroup
go
to_char
 	