select * 
into SYSEMAILSMTPPASSWORD_Backup
from SYSEMAILSMTPPASSWORD

delete from SYSEMAILSMTPPASSWORD

insert into SYSEMAILSMTPPASSWORD
select * from SYSEMAILSMTPPASSWORD_Backup

Drop table SYSEMAILSMTPPASSWORD_Backup
Select * from SYSEMAILSMTPPASSWORD