ALTER INDEX ALL ON [dbo].[GENERALJOURNALACCOUNTENTRY] REORGANIZE
ALTER INDEX ALL ON [dbo].[TAXTRANSGENERALJOURNALACCOUNTENTRY] REORGANIZE

update statistics [dbo].[GENERALJOURNALACCOUNTENTRY]
update statistics [dbo].[TAXTRANSGENERALJOURNALACCOUNTENTRY]