select count(*) from ax30_develop.dbo.custtable
go
drop view CT_ImportSpecific
go
create view CT_ImportSpecific as 
select ACCOUNTNUM, NAME, ADDRESS, PHONE, TELEFAX, INVOICEACCOUNT, CUSTGROUP, LINEDISC, PAYMTERMID, CASHDISC, CURRENCY, BLOCKED, 
                      ONETIMECUSTOMER, ACCOUNTSTATEMENT, CREDITMAX, MANDATORYCREDITLIMIT, DIMENSION, DIMENSION2_, DIMENSION3_, VENDACCOUNT, 
                      TELEX, PRICEGROUP, MULTILINEDISC, ENDDISC, VATNUM, COUNTRY, INVENTLOCATION, DLVTERM, DLVMODE, CLEARINGPERIOD, ZIPCODE, 
                      STATE, COUNTY, URL, EMAIL, CELLULARPHONE, PHONELOCAL, FREIGHTZONE, CREDITRATING, TAXGROUP, STATISTICSGROUP, PAYMMODE, 
                      BANKACCOUNT, NAMEALIAS, CONTACTPERSONID, INVOICEADDRESS, OURACCOUNTNUM, SALESPOOLID, INCLTAX, CUSTITEMGROUPID, 
                      NUMBERSEQUENCEGROUP, LANGUAGEID, PAYMDAYID, LINEOFBUSINESSID, DESTINATIONCODEID, SUPPITEMGROUPID, TAXLICENSENUM, 
                      WEBSALESORDERDISPLAY, PAYMSPEC, BANKCENTRALBANKPURPOSETEXT, BANKCENTRALBANKPURPOSECODE, PRINTMODULETYPE, CITY, 
                      STREET, PAGER, SMS, RECID from dbo.custtable
go
ALTER TABLE [dbo].[CUSTTABLE] DROP CONSTRAINT [CK__CUSTTABLE__RECID__11DF9047]
go
IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CUSTTABLE]') AND name = N'I_077RECID')
DROP INDEX [I_077RECID] ON [dbo].[CUSTTABLE] WITH ( ONLINE = OFF )
go
insert into ax30_develop.dbo.CT_ImportSpecific
	select ACCOUNTNUM, NAME, ADDRESS, PHONE, TELEFAX, INVOICEACCOUNT, CUSTGROUP, LINEDISC, PAYMTERMID, CASHDISC, CURRENCY, BLOCKED, 
                      ONETIMECUSTOMER, ACCOUNTSTATEMENT, CREDITMAX, MANDATORYCREDITLIMIT, DIMENSION, DIMENSION2_, 'FromRGS',VENDACCOUNT, 
                      TELEX, PRICEGROUP, MULTILINEDISC, ENDDISC, VATNUM, COUNTRY, INVENTLOCATION, DLVTERM, DLVMODE, CLEARINGPERIOD, ZIPCODE, 
                      STATE, COUNTY, URL, EMAIL, CELLULARPHONE, PHONELOCAL, FREIGHTZONE, CREDITRATING, TAXGROUP, STATISTICSGROUP, PAYMMODE, 
                      BANKACCOUNT, NAMEALIAS, CONTACTPERSONID, INVOICEADDRESS, OURACCOUNTNUM, SALESPOOLID, INCLTAX, CUSTITEMGROUPID, 
                      NUMBERSEQUENCEGROUP, LANGUAGEID, PAYMDAYID, LINEOFBUSINESSID, DESTINATIONCODEID, SUPPITEMGROUPID, TAXLICENSENUM, 
                      WEBSALESORDERDISPLAY, PAYMSPEC, BANKCENTRALBANKPURPOSETEXT, BANKCENTRALBANKPURPOSECODE, PRINTMODULETYPE, CITY, 
                      STREET, PAGER, SMS, '99999999' as recid from axdb3_rgs.dbo.custtable
		--where custgroup = 'udl'
go
Declare @NewRecId   as INT
declare @count		as INT
SET @Count = (select count(*) from CustTable WHERE Recid  = '99999999')

DECLARE CustTableWithoutRecid CURSOR FOR
    SELECT a.recid
    FROM CustTable AS a
    WHERE Recid  = '99999999'
--SET @NewRecid = 0;
UPDATE dbo.SystemSequences
    SET    @NewRecid  = NextVal,
           NextVal    = NextVal + @Count
	WHERE ID = -1 AND TABID = 0 AND Dataareaid = 'dat'

OPEN CustTableWithoutRecid;
FETCH NEXT FROM CustTableWithoutRecid;
WHILE @@FETCH_STATUS = 0
   BEGIN
	  SET @NewRecid = @NewRecid+1;
	  UPDATE CustTable
		SET RecId = @NewRecid 
		WHERE CURRENT OF CustTableWithoutRecid;
      FETCH NEXT FROM CustTableWithoutRecid;
   END;


CLOSE CustTableWithoutRecid;
DEALLOCATE CustTableWithoutRecid;
go

CREATE UNIQUE NONCLUSTERED INDEX [I_077RECID] ON [dbo].[CUSTTABLE] 
(
	[DATAAREAID] ASC,
	[RECID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
go
ALTER TABLE [dbo].[CUSTTABLE]  WITH CHECK ADD CHECK  (([RECID]<>(0)))
go
select count(*) from ax30_develop.dbo.custtable
--select count(*),custgroup from ax30_develop.dbo.custtable group by custgroup
go
	