USE [AX2012_Todoor_TEST]
GO

/****** Object:  Table [dbo].[AP_PERFTESTSIMPLETABLE]    Script Date: 04/12/2012 11:10:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AP_PERFTESTSIMPLETABLE](
	[CUSTACCOUNT] [nvarchar](20) NOT NULL,
	[DESCRIPTION255] [nvarchar](255) NOT NULL,
	[ID] [nvarchar](10) NOT NULL,
	[TESTCONTAINER] [varbinary](max) NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[RECVERSION] [int] NOT NULL,
	[RECID] [bigint] NOT NULL,
 CONSTRAINT [I_100481RECID] PRIMARY KEY CLUSTERED 
(
	[RECID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[AP_PERFTESTSIMPLETABLE]  WITH CHECK ADD CHECK  (([RECID]<>(0)))
GO

ALTER TABLE [dbo].[AP_PERFTESTSIMPLETABLE] ADD  DEFAULT ('') FOR [CUSTACCOUNT]
GO

ALTER TABLE [dbo].[AP_PERFTESTSIMPLETABLE] ADD  DEFAULT ('') FOR [DESCRIPTION255]
GO

ALTER TABLE [dbo].[AP_PERFTESTSIMPLETABLE] ADD  DEFAULT ('') FOR [ID]
GO

ALTER TABLE [dbo].[AP_PERFTESTSIMPLETABLE] ADD  DEFAULT (NULL) FOR [TESTCONTAINER]
GO

ALTER TABLE [dbo].[AP_PERFTESTSIMPLETABLE] ADD  DEFAULT ('dat') FOR [DATAAREAID]
GO

ALTER TABLE [dbo].[AP_PERFTESTSIMPLETABLE] ADD  DEFAULT ((1)) FOR [RECVERSION]
GO


